### ISSUE TITLE
Rebuilding APK is givinnt APKTOOL build time exception

### ISSUE THREAD

**Issue by mohittyagi11** [ClaudiuGeorgiu/Obfuscapk#1]
It is possible to provide a package under which only encryption should happen. 

As otherwise it messes up with thirdparty libaries

**Comment by packmad** [comment]
Have you tried the `-i` option?
Maybe that'll do the trick.

**Comment by mohittyagi11** [comment]
Yeah, I did try that. I even tried add the path in the list of libs to exclude but no luck.
