### ISSUE TITLE
Obfuscate on decompiled apk directly 

### ISSUE THREAD

**Issue by ZMODs** [ClaudiuGeorgiu/Obfuscapk#103]
This might sounds like a dumb question, but is it possible to obfuscate on decompiled APK only, and without tools check?
Because i'm decompiling apk and make some changes, it would be great if i could obfuscate decompiled apk directly something like `obfuscapk -p -o ... <DECOMPILED_APK_DIRECTORY>` before i compile, sign and zipalign manually. The process of Obfuscapk is recompiling apk again which is taking too long time for me. I don't worry doing some steps manually.

**Comment by ClaudiuGeorgiu** [comment]
Hi, currently Obfuscapk is designed to perform each required step automatically, so your use case is not supported out of the box, but it souldn't be hard to implement. Generally, most obfuscators just need the list of smali files to work, e.g., the Nop obfuscator iterates through the smali files and adds some `nop` instructions:

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/d6e527c254ffb906a85ee4a548fe6d6da12608b7/src/obfuscapk/obfuscators/nop/nop.py#L25-L32

To skip the tools check, comment the following lines:

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/d6e527c254ffb906a85ee4a548fe6d6da12608b7/src/obfuscapk/main.py#L39-L42

Try commenting the following line and make sure that `self._decoded_apk_path` variable holds the path to the decompiled directory, this should skip the initial apktool decompilation (I haven't tested):

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/d6e527c254ffb906a85ee4a548fe6d6da12608b7/src/obfuscapk/obfuscation.py#L341

To skip the final recompilation, just omit `-o Rebuild -o NewAlignment -o NewSignature` from the list of obfuscators passed to Obfuscapk (and do these steps manually).

**Comment by ZMODs** [comment]
Ok, the thing is i'm not familar with python so this is the first time to deal with py scripts. Hopefully i can do this easly

**Comment by ZMODs** [comment]
Ok i did it
