### ISSUE TITLE
Question Related to ConstStringEncryption

### ISSUE THREAD

**Issue by whorohitkumar** [ClaudiuGeorgiu/Obfuscapk#104]
Wanted to ask that. i wanted to change the default dir of the const string encryption which used to be saved in com\decryptstringmanager\DecryptString.smali bydefault. I want that i can change into some other directory of smali or classes.dex folder with different name(not with default name of com) please help me with this

**Comment by ClaudiuGeorgiu** [comment]
Hi, you should be able to do that by just renaming the package `com/decryptstringmanager` to whatever you want (e.g., `org/test/whatever`), just make sure to rename every instance.
