### ISSUE TITLE
Obfuscapk future support for bundle .aab files 

### ISSUE THREAD

**Issue by Soubhy** [ClaudiuGeorgiu/Obfuscapk#105]
Hello, after the recent modification of Google Play regarding the upload of APK files from August, does obfuscapk propose any update to obfuscate these bundles?

https://android-developers.googleblog.com/2021/06/the-future-of-android-app-bundles-is.html

Thanks in advance

**Comment by ClaudiuGeorgiu** [comment]
Hi, there are no plans for bundle support at the moment, but if someone is interested in sending a pull request with this feature I'll be happy to review and eventually merge it. For further discussion, please use #6.
