### ISSUE TITLE
Android Studio -specific ERROR:  No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#110]
I have used Obfuscapk successfully before on APKs build with Eclipse.
Having used Android Studio to build a recent APK I see strange behavior with an error:
- laptop fan immediately kicks in on high CPU utilization shows Java System hitting 80%;
- then after a few secs in CPU utilization it's Python on top at 26% 
- none of that happens when using Eclipse APKs
- No output file produced of any kind
-  I see this error:   `[Errno 2] No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'`

Here is command as invoked:
`python -m obfuscapk.cli -o FieldRename -o Reorder -o CallIndirection -o Rebuild -o NewSignature -o NewAlignment myfile.apk`

the output:
```
[ERROR][obfuscapk.tool.Jarsigner][resign()] Error during the removal of the old signature: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'
[ERROR][obfuscapk.obfuscation][sign_obfuscated_apk()] Error during apk signing: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'
[ERROR][yapsy_loaded_plugin_NewSignature_1.new_signature.NewSignature][obfuscate()] Error during execution of "NewSignature" obfuscator: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'
[CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'

`Traceback (most recent call last):
  File ". . .Obfuscapk\src\obfuscapk\main.py", line 119, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File ". . .Obfuscapk\src\obfuscapk\obfuscators\new_signature\new_signature.py", line 20, in obfuscate
    obfuscation_info.sign_obfuscated_apk()
  File ". . .Obfuscapk\src\obfuscapk\obfuscation.py", line 507, in sign_obfuscated_apk
    jarsigner.resign(
  File ". . .Obfuscapk\src\obfuscapk\tool.py", line 254, in resign   with zipfile.ZipFile(apk_path, "r") as current_apk:
  File ". . .\Python38-32\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myfile_obfuscated.apk'

Traceback (most recent call last):
  File ". . .\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ". . .\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ". . .Obfuscapk\src\obfuscapk\cli.py", line 133, in <module>
    main()
  File ". . .Obfuscapk\src\obfuscapk\cli.py", line 121, in main
    perform_obfuscation(
  File ". . .Obfuscapk\src\obfuscapk\main.py", line 119, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File ". . .Obfuscapk\src\obfuscapk\obfuscators\new_signature\new_signature.py", line 20, in obfuscate
    obfuscation_info.sign_obfuscated_apk()
  File ". . .Obfuscapk\src\obfuscapk\obfuscation.py", line 507, in sign_obfuscated_apk
    jarsigner.resign(
  File ". . .Obfuscapk\src\obfuscapk\tool.py", line 254, in resign
    with zipfile.ZipFile(apk_path, "r") as current_apk:
  File ". . .\Python38-32\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: obfuscation_working_dir\\myfile_obfuscated.apk


Here is a very basic APK created with Android Studio , that's still having same issue, 2.6M size
 https://drive.google.com/file/d/15BfjNBM4cfDxncM0dN3UI-LUyPVKWN5W/view?usp=sharing

PS. even using just a Reorder module still pushing Java CPU Utilization to 80%, briefly

**Comment by skreenr** [comment]
I now see that trying running with minimal configuration per TROUBLESHOOTING fails with the same error No such file or directory:  'obfuscation_working_dir\\TestAstu_obfuscated.apk'  , even when using -i option

Is this the anti-repackaging technique thing that arises when using Android Studio, and it's apktool where the journey stops?

**Comment by skreenr** [comment]
It is apktool issue and it needs to be run with -aapt2 option
Can adjust the script for that, or there is some config file?

**Comment by ClaudiuGeorgiu** [comment]
Hi @skreenr, the latest version of Obfuscapk already has `--use-aapt2` flag that can be passed as argument during the obfuscation, there is no need to modify any file. However, I'm glad you found a solution to the issue 👍

**Comment by skreenr** [comment]
Actually I am not in the clear yet:

It worked when I do the "minimal configuration" Resign/Rebuild/NewAlignment thing,
If I try adding some Obfuscators, it `works OK on Reorder `, yet gives same FileNotFoundError: [Errno 2] No such file or directory on FieldRename, CallIndirection. 
In the log files I don't see exact failure point in obfuscators, all it reports is NewSignature failed with FileNotFound error.
Struggling to make sense of it, here is log:

`Traceback (most recent call last):
  File "C:\Users\dev\Documents\DECOMPILE\Obfuscapk\src\obfuscapk\main.py", line 141, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "C:\Users\dev\Documents\DECOMPILE\Obfuscapk\src\obfuscapk\obfuscators\new_signature\new_signature.py", line 20, in obfuscate
    obfuscation_info.sign_obfuscated_apk()
  File "C:\Users\dev\Documents\DECOMPILE\Obfuscapk\src\obfuscapk\obfuscation.py", line 507, in sign_obfuscated_apk
    jarsigner.resign(
  File "C:\Users\dev\Documents\DECOMPILE\Obfuscapk\src\obfuscapk\tool.py", line 257, in resign
    with zipfile.ZipFile(apk_path, "r") as current_apk:
  File "C:\Users\dev\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'obfuscation_working_dir\\xdaapk_obfuscated.apk'`

**Comment by skreenr** [comment]
What I am trying to say, the logging seems to be missing actual failure points in obfuscator modules. We are not seeing "real" errors. How come?

**Comment by ClaudiuGeorgiu** [comment]
> What I am trying to say, the logging seems to be missing actual failure points in obfuscator modules. We are not seeing "real" errors. How come?

Have you tried enabling [verbose logs](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/d6e527c254ffb906a85ee4a548fe6d6da12608b7/docs/TROUBLESHOOTING.md#enable-verbose-logging)? Do you get additional info about the error?

**Comment by skreenr** [comment]
I tried earlier and get a flood of msgs, like 1.5M log files
Thinking if it's an Error, it should appear in ERROR log

**Comment by skreenr** [comment]
If you have a tip on what line to look for in Verbose log, I can try

**Comment by ClaudiuGeorgiu** [comment]
This works for me without errors on Windows with the latest version of Obfuscapk and the apk you provided:
```
python3 -m obfuscapk.cli --use-aapt2 -o CallIndirection -o FieldRename -o Rebuild -o NewAlignment -o NewSignature C:\Users\me\Desktop\TestAStu.apk
```

**Comment by skreenr** [comment]
Interesting, you did in a different order and it works! I will try that

**Comment by skreenr** [comment]
I modified logging code so now it logs obfuscator name (first 5 lines below) and what I see is every obfuscator fires the same Error:

ERROR:root:obfuscator_name:  CallIndirection
ERROR:root:obfuscator_name:  FieldRename
ERROR:root:obfuscator_name:  Rebuild
ERROR:root:obfuscator_name:  NewSignature
ERROR:obfuscapk.tool.Jarsigner:Error during the removal of the old signature: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myapp_obfuscated.apk'
ERROR:obfuscapk.obfuscation:Error during apk signing: [Errno 2] No such file or directory: 'obfuscation_working_dir\\myapp_obfuscated.apk'
ERROR:yapsy_loaded_plugin_NewSignature_1.new_signature.NewSignature:Error during execution of "NewSignature" obfuscator: [Errno 2] No such file or directory: 'obfuscation_working_dir\\xda_obfuscated.apk'
CRITICAL:obfuscapk.main:Error during obfuscation: [Errno 2] No such file or directory: 'obfuscation_working_dir\\xda_obfuscated.apk'

Is it perhaps absolute path vs relative path thing? like it's getting relative path instead of absolute and can't see a file?

**Comment by ClaudiuGeorgiu** [comment]
Please try using the latest version of Obfuscapk, now we use Apksigner instead of Jarsigner, this might help.

**Comment by skreenr** [comment]
My hunch is it still can be Apktool related, in that when I manually decompile then  rebuild APK with APK tool, the production APK with FCM shows one extra dir in Apktool structure named 'unknown' alongside original, res, smali etc.  Inside that dir I see FCM related files, "properties" files

**Comment by skreenr** [comment]
I am getting errors when following your instructions:
`$ # Install Obfuscapk's requirements.
$ python3 -m pip install -r src/requirements.txt`
The error is:
`C:\Users\dev\Documents\DECOMPILE\Obfuscapk>python -m pip install -r src/requirements.txt
Collecting pycryptodome==3.9.9 (from -r src/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/91/d5/e8e0374f10cbb12fb6d41af6ba939f85a53bd34dda28e4ca9253ab43c1b4/pycryptodome-3.9.9-cp38-cp38-w
2.whl (14.1MB)
ERROR: Could not install packages due to an EnvironmentError: [WinError 31] A device attached to the system is not functioning
Consider using the `--user` option or check the permissions.`

**Comment by skreenr** [comment]
Examining DEBUG-level log, here is a block of interest, which repeats several times:

``DEBUG:yapsy:correct subclass tests failed for: __builtins__ in C:\Users\dev\Documents\DECOMPILE\Obfuscapk\src\obfuscapk\obfuscators\advanced_reflection
Traceback (most recent call last):
  File "C:\Users\dev\AppData\Local\Programs\Python\Python38-32\lib\site-packages\yapsy\PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
  File "C:\Users\dev\AppData\Local\Programs\Python\Python38-32\lib\abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class

**Comment by skreenr** [comment]
I installed the current release ZIP, have built the production APK with all obfuscators – the output file is 2M bigger in size! interesting Why – yet it fails to install on the phone. Probably issue is with a signature.
What sigs are you guys using there?

Tried passing key-passwd and -alias on command line, now getting Python error:

`PermissionError (WinError 31) A device attached to the system is not functioning
`Found this article
_https://stackoverflow.com/questions/50085366/permissionerror-winerror-31-a-device-attached-to-the-system-is-not-functioning_
which advises workaround
` chcp 1252`  
yet it won't work

**Comment by skreenr** [comment]
I was able to rebuild, without correct APKSigner sig, my APK after closing Python window and reopening new session

Can you explain how APKSign needs to be called in your new version with a keystore, like examples please?
I run APKSign manually and resulting APK was verifying and installed, however it won't run, just exits right away 

Any tips appreciated, like How to isolate the error (is it signing or elsewhere?)

**Comment by skreenr** [comment]
That minimal APK built with AStudio I shared earlier – here I decided to test theory that Google libs like Firebase break Obfuscapk. What I did was, added Firebase functionality to the project and now, after obfuscating and resigning new APK, I get the same kind of behavior on device, in that the app abruptly exits at launch w/o showing anything. Just like my production APK. Here is a link to APK as it comes from AStudio:  https://drive.google.com/file/d/1jhaoySLkf6tOmK2dE1RY9_f3a4rTc5Ze/view?usp=sharing

**Comment by ClaudiuGeorgiu** [comment]
> after obfuscating and resigning new APK, I get the same kind of behavior on device, in that the app abruptly exits at launch w/o showing anything

Did you use all the available obfuscators? Using `--ignore-libs` should have solved the issue, but since you already tried that, there must be at least one obfuscator that doesn't play well with Firebase. You can try finding the problematic obfuscator(s) as described [here](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/881403e235024db8a2bf0691de6c25f61bc369b7/docs/TROUBLESHOOTING.md#find-the-problematic-obfuscator), then exclude from the list those that break the app when using Firebase.

**Comment by skreenr** [comment]
I should have mentioned I do use  `--ignore-libs` 
Looking at the directory structure creaed by APKTOOL I see one new directory added "unknown" , filled with multiple Firebase PROPERIES files 1K size each

**Comment by skreenr** [comment]
Claudiu, on your msg: using 3 obfuscators in a chain: I do need them all to achieve protection!
The thing is, without Firebase in the mix both TestAStu and the bigger production APK successfully obfuscate, install and run on a device. Adding Firebase leads to the app's immediate exit on start-up with error in the log hinting Failure to initialize Firebase:   `com.google.firebase.provider.FirebaseInitProvider.onCreate()` , see https://drive.google.com/file/d/1GZk0hlnC4KYdUlOoQwQxIXBbw3g_FvXm/view

What I did next was, I wanted to check an assumption the failure is with APKTool incorrectly handling Firebase– by decompiling TestASTwFirebase with APKTool, then rebuilding and resigning it. 
I expected it will fail to run, I was wrong: the app installs on a device, runs and receives Firebase notifications just like original APK does.

Hmm, I have no ideas at the moment. All I can think of is, if we can find way to import non-Firebased obfuscated classes in AStudio to add Firebase functionality to a final build..

**Comment by skreenr** [comment]
**Problematic obfuscator** turns out to be FieldRename
When I use just it with Rebuild/Align/Sign I get the same app crash on start-up as reported above.
Other two obfuscators I use, each of them produced a working APK when used alone.

To just drop FieldRename from the list of 3 I am using would weaken obfuscation, that's the concern
I would much rather find how to fix it, get it behave like others do

**Comment by skreenr** [comment]
Solved this: after Googling for exact error msg, found some SOF posts about how it's important that various Firebase libraries versions listed in build gradle version-match. After changing version # some, it worked flawlessly.
The curious thing of course is, Why the error – the app abruptly quits at startup– only happens after Obfuscapk, and not at all with the original build.

**Comment by skreenr** [comment]
Closing this
