### ISSUE TITLE
--Ignore-libs fails to ignore Google code

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#112]
Looking at the Log generated at DEBUG level, I obfuscator being applied to a Google's code as in:

_DEBUG:yapsy_loaded_plugin_CallIndirection_1.call_indirection.CallIndirection:Inserting call indirections in file "obfuscation_working_dir\xdarelzunsi\smali\com\google\android\datatransport\runtime\scheduling\jobscheduling\WorkInitializer$$Lambda$2.smali"_

plus a lot more lines like the above pertaining to` \google\android\datatransport`
Since I am using the -i flag, that seems like it should not be happening?

full command was:
  `C:\Users\dev\Documents\DECOMPILE\Obfuscapk\src>python -m obfuscapk.cli -o FieldRename -o CallIndirection -o Rebuild -o NewAlignment -d outapk.apk -i input.apk`

**Comment by ClaudiuGeorgiu** [comment]
Try adding the line `com/google/android/datatransport` to [libs_to_ignore.txt](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/881403e235024db8a2bf0691de6c25f61bc369b7/src/obfuscapk/resources/libs_to_ignore.txt) file and retry, this should solve the issue for this specific package.
