### ISSUE TITLE
Not changing method name

### ISSUE THREAD

**Issue by Dershowitz011** [ClaudiuGeorgiu/Obfuscapk#113]
I've a method named `.Start()Z ` and when I use the parameter "MethodRename" in the CLI, the method name remains unchanged in the obfuscated apk. What's the proper way of doing what I want? 

Also please suggest the best parameters in their order to be used to highly obfuscate a mod apk. Thanks a lot in advance.

**Comment by ClaudiuGeorgiu** [comment]
Hi @Dershowitz011, please see https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/42#issuecomment-655396643, it explains why some methods are not obfuscated.
