### ISSUE TITLE
App Bundle move by Google requires new workflow

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#114]
Google announced move-away from APK format to new App Bundle, https://www.theverge.com/2021/6/30/22557390/google-apk-app-bundles-package-format-play-store
In fact, APKs are no longer accepted for upload to Play market I believe.

As Obfuscapk relies on APK Tool, which does not support App bundles, my question is, if you have any ideas or suggestions about alternative workflows to accommodate this new format requirement?

**Comment by ClaudiuGeorgiu** [comment]
Hi, there are no plans for bundle support at the moment, but contributions are welcome if someone is interested. For further discussion, please use #6.
