### ISSUE TITLE
Obfuscation of APK with reflected

### ISSUE THREAD

**Issue by lt3stus3el** [ClaudiuGeorgiu/Obfuscapk#119]
Hi and thanks for the app.
When dealing with apps in which there are reflection included in them, some obfuscators won't work which is reasonable, including MethodRename, ClassRename, FieldRename, CallIndirection, Reflection AdvancedReflection and ConstStringEncryption.

If I want to obfuscate such apps, how should I change the process? Are you planning to add the feature?

Thanks

**Comment by ClaudiuGeorgiu** [comment]
Hi @lt3stus3el, unfortunately obfuscating apps that already use reflection it's not a trivial task, and currently I don't have any plan to work on this specific feature in the near future. However, in case you come up with some ideas that you want to try implementing, contributions are welcome!
