### ISSUE TITLE
Can we use other than docker to build

### ISSUE THREAD

**Issue by graysuit** [ClaudiuGeorgiu/Obfuscapk#12]
SIr I have been using it and since a lot of errors are coming the script,
I have seen releases but these are source code, no exe was added,
So can I use any other method to build the source code,

Docker is not available for 32 bit windows.

**Comment by packmad** [comment]
This is a Python project, it is not supposed to be compiled (some projects exist to compile Python code but we don't know if they work with Obfuscapk).
Our project is tested and working on Ubuntu 18.04 and Windows 10 (64-bit versions).
