### ISSUE TITLE
How can we integrate obfuscapk in to our ci/cd pipeline?

### ISSUE THREAD

**Issue by lovemhjn** [ClaudiuGeorgiu/Obfuscapk#120]

**Comment by ClaudiuGeorgiu** [comment]
The question is too broad, can you describe with more details what is your use case and what tools you are currently using? If I had to give a general advice, I would say that you have to use Obfuscapk as one of the latest steps in your pipeline: once you have your apk file, pass it to Obfuscapk for obfuscation, then the resulting apk file should be ready for delivery.
