### ISSUE TITLE
Produce an obfuscation mapping file

### ISSUE THREAD

**Issue by petrdvorak** [ClaudiuGeorgiu/Obfuscapk#122]
To simplify a crash log analysis during the app operation, the tool should produce [a mapping file (`mapping.txt`)](https://developer.android.com/studio/build/shrink-code) alongside the resulting obfuscated application. Since the app may already be obfuscated with tools like R8 or Proguard, additional feature could be combining the original mapping file with the results of your obfuscations.

Changes would then consist of introducing new arguments:

```
--original-mapping-file [mapping.txt]      ... path to the original obfuscation mapping file
--mapping-file [mapping2.txt]              ... path to the resulting, combined mapping file
```

**Comment by ClaudiuGeorgiu** [comment]
Hi @petrdvorak, thanks for the suggestion! This could be very useful when analyzing the error messages of an obfuscated app.

**Comment by lovemhjn** [comment]
Hi @petrdvorak , Do you have future plans of generating a mapping file along with obfuscated apk. it will be really helpful to trace the crashes from the crashlytics dashboard in the production app. Thanks
