### ISSUE TITLE
.aab file to .apk file

### ISSUE THREAD

**Issue by osageu** [ClaudiuGeorgiu/Obfuscapk#125]
Hi, i use your new aab obfuscator.
To obfuscate aab file, i set arguments '-o RandomManifest -o Rebuild -o NewAlignment -i --ignore-packages' and 'xxx/output.aab'.
well.. this works good. 
So, to test aab file, i used bundletool build-apks command.(convert .aab to .apk)
But the error "The archive doesn't seem to be an App Bundle, it is missing required file 'BundleConfig.pb'" appears.
Do you have a same issue like this?
Or how do you install obfuscated aab file to test in devices?

**Comment by DuyLong97** [comment]
> Hi, i use your new aab obfuscator. To obfuscate aab file, i set arguments '-o RandomManifest -o Rebuild -o NewAlignment -i --ignore-packages' and 'xxx/output.aab'. well.. this works good. So, to test aab file, i used bundletool build-apks command.(convert .aab to .apk) But the error "The archive doesn't seem to be an App Bundle, it is missing required file 'BundleConfig.pb'" appears. Do you have a same issue like this? Or how do you install obfuscated aab file to test in devices?

Hello @osageu  You are using Obfuscapk on Macos or Ubuntu? If Macos, can you guide me where is the place you save the BundleCompliler.jar?
