### ISSUE TITLE
How to detect is obfuscation done successfully or not

### ISSUE THREAD

**Issue by bimalchawla89** [ClaudiuGeorgiu/Obfuscapk#129]
![image](https://user-images.githubusercontent.com/6601775/157062029-99fe4285-ff51-4933-a036-42c6a33d6f06.png)

when running the command getting below response, how to detect whether obfuscation process completed or not and where the destination apk generated that also not generating. Thanks.

**Comment by bimalchawla89** [comment]
@ClaudiuGeorgiu please help here. Thanks.

**Comment by ClaudiuGeorgiu** [comment]
When you use Docker you cannot directly access the files on your system from a running container. You have to mount the file/directory to be able to access it from the container, using the `-v` parameter (as suggested in the readme). In your case, the command should be similar to this (not sure if this will really work, I don't use Docker on Windows):

![image](https://user-images.githubusercontent.com/6818578/157093510-36f0f53d-5c93-4799-9d52-f1cfb724d1a7.png)

If everything works, you should find the obfuscated file in `C:\Users\bimalchawla\Desktop\Obfuscapk\src\ee.apk`.
