### ISSUE TITLE
Specify packages to obfuscate

### ISSUE THREAD

**Issue by VanHoevenTR** [ClaudiuGeorgiu/Obfuscapk#131]
### Is this feature request related to a problem?

No

### Proposed solution

An option to specify one or more packages. Example I only want to obfuscate: `com.example` and `com.example2`. I know there is `--ignore-packages-file` but it's not what I want

### Additional context

No, I think

### Would you like to submit a pull request for this feature?

No, don't have knowledge

**Comment by KhanhXu** [comment]
My issues same!
