### ISSUE TITLE
Obfuscate APK not Find In Linux and macOS

### ISSUE THREAD

**Issue by Yunoon** [ClaudiuGeorgiu/Obfuscapk#132]
my Command `docker run -v "/root":"/workdir" claudiugeorgiu/obfuscapk -w /workdir/obfuscation_dir/ -o ConstStringEncryption -d /workdir/obfuscated.apk /workdir/base233.apk -p`

but in /root, the `obfuscated.apk` not in the directory.

**Comment by ClaudiuGeorgiu** [comment]
`Rebuild`, `NewAlignment` and `NewSignature` obfuscators are always needed to complete an obfuscation operation, to build the final obfuscated apk. Add them after `ConstStringEncryption` and `obfuscated.apk` should be generated correctly.

**Comment by Yunoon** [comment]
I found that it might be a problem with my APK file.
When I try to obfuscate an APK file from officially provided， I can obfuscate it.
The APK file in question was compiled and generated by android studio.
