### ISSUE TITLE
Error during obfuscation: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by KhanhXu** [ClaudiuGeorgiu/Obfuscapk#134]
Hi,
I get this error.

Running obfuscators (Rebuild):   0%|                                                                                                           |[00:00<?, ?obfuscator/s]06/05/2022 10:29:50> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decoding: [Errno 8] Exec format error: '/Data/Obfuscate/tool/apktool.jar'
06/05/2022 10:29:50> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: [Errno 8] Exec format error: '/Data/Obfuscate/tool/apktool.jar'
06/05/2022 10:29:50> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: [Errno 8] Exec format error: '/Data/Obfuscate/tool/apktool.jar'
06/05/2022 10:29:50> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: [Errno 8] Exec format error: '/Data/Obfuscate/tool/apktool.jar'

Can you help me? 
Thanks!

**Comment by ClaudiuGeorgiu** [comment]
Hi, what's the output if you type `apktool` in the terminal? From the error it looks like there is something wrong with how you installed `apktool`.

**Comment by KhanhXu** [comment]
I am replaced code.

<img width="613" alt="Screen Shot 2022-05-06 at 13 34 28" src="https://user-images.githubusercontent.com/89991675/167079479-d9b6bfd0-26f5-40c2-905a-fe014d06879d.png">

**Comment by ClaudiuGeorgiu** [comment]
Please install `apktool` properly (<https://ibotpeaches.github.io/Apktool/install/>) and the original code will work. I'm not against changing the code, you can absolutely do it, but then you will have to find a solution on your own 😉

**Comment by KhanhXu** [comment]
Thanks ClaudiuGeorgiu!
