### ISSUE TITLE
res navigation name not change

### ISSUE THREAD

**Issue by zhoujingheng** [ClaudiuGeorgiu/Obfuscapk#137]
### Description

Obsuscapk navigation fragment done，but the tag android:name not change

![image](https://user-images.githubusercontent.com/12888787/170441866-93f3b531-36db-402d-894c-bc06416a79f7.png)

### Steps to reproduce

1. Create New Android Project
![image](https://user-images.githubusercontent.com/12888787/170627058-5589c27d-77df-4b65-a5c4-2866f0ef7439.png)

2. assembleRelease apk
![image](https://user-images.githubusercontent.com/12888787/170627138-3b9867ef-eb8c-4c68-b681-d22279b78428.png)

3. Obsusc Classrename release apk
4. jadx open Obsusc release apk look res navigation folder

**Expected behavior:**

**Actual behavior:**

```
paste here the complete error message, including the command that generated the error
```

### Versions

* **OS** (window10):
* **Python version** (Python 3.10.4):
* **Apktool version** ( v2.6.1):

### Additional information

**Apk file(s):**

**Expected behavior:**

**Actual behavior:**

```
paste here the complete error message, including the command that generated the error
```

### Versions

* **OS** (window10):
* **Python version** (Python 3.10.4):
* **Apktool version** ( v2.6.1):

### Additional information

**Apk file(s):**

**Comment by zhoujingheng** [comment]
* **OS** (window):
* **Python version** (Python 3.10.4):
* **Apktool version** ( v2.6.1):

**Comment by ClaudiuGeorgiu** [comment]
![image](https://user-images.githubusercontent.com/6818578/170454803-7be25798-2751-4267-a077-3f87cc591a0d.png)
Well, that's pretty clear 😅.

**Comment by zhoujingheng** [comment]
> ![image](https://user-images.githubusercontent.com/6818578/170454803-7be25798-2751-4267-a077-3f87cc591a0d.png) Well, that's pretty clear 😅.

Hello,i have update issue
