### ISSUE TITLE
Virustotal marking apk after this code as Malicious (score: 99)

### ISSUE THREAD

**Issue by APPDEVTYCOONKEKW** [ClaudiuGeorgiu/Obfuscapk#138]
Virustotal marking apk after this code as Malicious (score: 99)
Even if its hello world.

**Comment by ClaudiuGeorgiu** [comment]
Hi, please see the first entry in the [FAQs](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/FAQ.md#speech_balloon-can-i-use-this-tool-to-bypass-antivirus-software).
