### ISSUE TITLE
Apk crashes after obfuscation

### ISSUE THREAD

**Issue by AnkitaAngane** [ClaudiuGeorgiu/Obfuscapk#140]
Hello!

I have followed each and every steps mentioned in the guide.
Obfuscation process has done absolutely fine. I haven't encountered any error in between the process.
But when I try to install obfuscated.apk file on android, It throws "**App not installed as package appears to be invalid**"
I have python 3.7.8 and using below command for obfuscation.

python -m obfuscapk.cli -p -o ClassRename -o ConstStringEncryption -o Rebuild -o NewAlignment -o ResStringEncryption -o FieldRename D:\Check\m.apk

Would appreciate your guide further on this.

![image](https://user-images.githubusercontent.com/71700981/181753375-fbb22f78-13a8-414e-bd9a-f52c376901a3.png)

**Comment by Dado1513** [comment]
Hi @AnkitaAngane, you should add `NewSignature` option.

**Comment by AnkitaAngane** [comment]
@Dado1513 Thank you, It worked!

**Comment by AnkitaAngane** [comment]
@Dado1513 I have one more query wrt to NewSignature, I don't want to add NewSignature and use the one from .jks file,
So instead of using -o NewSignature,  I am using appending command --keystore-file to pass .jks file followed with --keystore-password, --key-alias, --key-password 

As earlier, everything is working fine but It throws "**App not installed as package appears to be invalid**"

Thanks in advance :)
