### ISSUE TITLE
APK COMPILER

### ISSUE THREAD

**Issue by Osama139** [ClaudiuGeorgiu/Obfuscapk#142]
After obfuscating an apk with obfuscapk, the provided file by the obfuscapk is not compiling, it is giving errors, how can i fix that? Doesn't obfuscapk provide a compiled .apk file after obfuscating?

**Comment by ClaudiuGeorgiu** [comment]
> how can i fix that?

I have absolutely no idea, since you are not providing any details to help investigate the issue. You can start by checking [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md).

> Doesn't obfuscapk provide a compiled .apk file after obfuscating?

Yes.
