### ISSUE TITLE
android:name and obfuscation:name

### ISSUE THREAD

**Issue by adgluzdov** [ClaudiuGeorgiu/Obfuscapk#148]
![image](https://user-images.githubusercontent.com/11931849/207180895-4a94e6a4-a905-44bf-93ab-5cedb2f4efce.png)

Why change "android:name" or "android:theme" to "obfuscation:name", "obfuscation:theme". Many people do obfuscation in order to hide from others, and because of "obfuscation" the application begins to differ from others. Thank you for your work!

**Comment by ClaudiuGeorgiu** [comment]
We wanted the obfuscated app to differ as much as possible from the original, but still maintaining its functionality. If many people use this tool, the `obfuscation` namespace will become like a sort of signature indicating that Obfuscapk has been used, so you're right: it will be more difficult to hide. Maybe it's better to use a random string? Or keep the original `android`? I don't have an answer, but during our tests (when we originally wrote the tool) this worked well so we kept it.

However, if you don't like it, you can change it back to `android` here:

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/2185bd450c4ba1fb2a612789a067fa0a5747f933/src/obfuscapk/obfuscators/random_manifest/random_manifest.py#L104-L107

**Comment by adgluzdov** [comment]
Thanks for the answer, it helped me
