### ISSUE TITLE
Apk crashes after Obfuscation

### ISSUE THREAD

**Issue by Therahuls1n9h** [ClaudiuGeorgiu/Obfuscapk#150]
Hello!

I have followed each and every step mentioned in the guide.
The obfuscation process has done absolutely fine. I haven't encountered any errors in the process.
But when I try to install the obfuscated.apk file on android, It throws "App not installed as package appears to be invalid"
I have Python 3.10.6 and use the below command for obfuscation.

sudo docker run --rm -it -u $(id -u):$(id -g) -v "${PWD}":"/workdir" obfuscapk -o MethodOverload -o Reorder -o
MethodRename -o RandomManifest -o Reflection -o AdvancedReflection -o ArithmeticBranch -o CallIndirection -o ConstStringEncryption -o DebugRemoval -o FieldRename -o Goto -o Rebuild -o NewSignature -o NewAlignment bd.apk

<img width="960" alt="Screenshot_20230120_045820" src="https://user-images.githubusercontent.com/95334742/213585291-f2dcaac7-a11a-467d-b6a9-57a0d73537dc.png">

I would appreciate your guide further on this.

**Comment by Therahuls1n9h** [comment]
update just put -o NewSignature, in the end, everything worked but none of rename obsfuscation working after build app is crashing just gray screen and it crashes

any help would be appreciated

**Comment by ClaudiuGeorgiu** [comment]
Hi, please have a look at [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md#try-running-with-minimal-configuration), probably one of the renaming obfuscators is breaking your app.

**Comment by Therahuls1n9h** [comment]
Hey thanks for the reply i tried troubleshooting but none of rename obfuscation working it gets successfully build but the app crashes

**Comment by Therahuls1n9h** [comment]
so how can we use renaming obfuscation.

**Comment by ClaudiuGeorgiu** [comment]
> so how can we use renaming obfuscation.

Renaming obfuscation can easily break the app. If the obfuscation ends without errors, but the app crashes during execution, there's nothing we can do without further investigation, sorry.

**Comment by Therahuls1n9h** [comment]
then i will close this issue
