### ISSUE TITLE
About metasploit

### ISSUE THREAD

**Issue by ultrahacker678** [ClaudiuGeorgiu/Obfuscapk#154]
Hi, i made and metasploit apk and encrypted it with your tool. Can i move smali folders with decryptor and smali folders with metasploit WITHOUT META-INF folder? Or in META some expensive keys stored?

**Comment by ClaudiuGeorgiu** [comment]
Hi, the obfuscators currently implemented in Obfuscapk don't store anything in the `META-INF` folder.

**Comment by ultrahacker678** [comment]
> 

Also, can you please add function to operate(encrypt methods, classes and other) only with specified path, bacause i have big apk  with big .dex files and i want to obfuscate only some small parts of this dex, i dont want to obfuscate all dex files with all content inside. This function present in NP Manager, and named "Control Flow Obfuscation"
Link to download NP: https://drive.google.com/file/d/1EBobxPc2hK_1_KqaABsN-YE7_L1Aqgau/view?usp=drivesdk
WARNING: NP manager detected how MALWARE so use only on VM(i think this isnt really malware, mb this is because a lot of obfuscation tools in it)
