### ISSUE TITLE
apktool errror

### ISSUE THREAD

**Issue by theplug4000** [ClaudiuGeorgiu/Obfuscapk#155]
Hello, I recently ran apktool b to rebuild apk, but it gave me this error:

[Fatal Error] :48:584: Attribute "android:networkSecurityConfig" was already specified for element "application".
I: Checking whether resources has changed...
I: Building resources...
W: <path unbuild apk>:48: error: Error parsing XML: duplicate attribute
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PC\AppData\Local\Temp\brut_util_Jar_68820154850366671442811688857310715614.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 32, --version-code, 629, --version-name, 13.3, --no-version-vectors, -F, C:\Users\PC\AppData\Local\Temp\APKTOOL5583683532486575500.tmp, -e, C:\Users\PC\AppData\Local\Temp\APKTOOL2254009933096751434.tmp, -0, arsc, -I, C:\Users\PC\AppData\Local\apktool\framework\1.apk, -S, <path unbuild apk>\res, -M, <path unbuild apk>

How do I resolve this error?

**Comment by ClaudiuGeorgiu** [comment]
Hi, please use the bug report issue template and include all the needed information.
