### ISSUE TITLE
About enc key

### ISSUE THREAD

**Issue by ultrahacker678** [ClaudiuGeorgiu/Obfuscapk#156]
Hi, i have +1 question: how to change encryption key with which methods and classes names are changing? Because if i encrypt class with name (for example)"a" it will always be "b"(for example), every time im trying to encrypt this class.

**Comment by ClaudiuGeorgiu** [comment]
Hi, please see https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/41#issuecomment-655037098, it should answer your question.
