### ISSUE TITLE
Whether About is Bundle Support aab?

### ISSUE THREAD

**Issue by TheRangerStar** [ClaudiuGeorgiu/Obfuscapk#157]
Do the project currently support aab operation?   👀👀👀

**Comment by ClaudiuGeorgiu** [comment]
Hi, there is some support for bundles (see https://github.com/ClaudiuGeorgiu/Obfuscapk/pull/121), but is not tested as much as with apk files (I always used Obfuscapk only on apk files).

**Comment by TheRangerStar** [comment]
> Hi, there is some support for bundles (see #121), but is not tested as much as with apk files (I always used Obfuscapk only on apk files).

Dear @ClaudiuGeorgiu  :
Thank u for your reply ,,,I looked at the document again and found the introduction of aab

**Comment by TheRangerStar** [comment]
> Hi, there is some support for bundles (see #121), but is not tested as much as with apk files (I always used Obfuscapk only on apk files).

Dear @ClaudiuGeorgiu :
Thank u for your reply ,,,I looked at the document again and found the introduction of aab.
Then I follow the instructions in the document.
But until I cd to**Obfuscapk/src** on the terminal,Then the following questions were reported:
![image](https://user-images.githubusercontent.com/55529715/221121262-9531831d-675d-47fd-895d-7055b836babf.png)
How can I solve it,Looking forward to your reply

**Comment by TheRangerStar** [comment]
> > Hi, there is some support for bundles (see #121), but is not tested as much as with apk files (I always used Obfuscapk only on apk files).
> 
> Dear @ClaudiuGeorgiu : Thank u for your reply ,,,I looked at the document again and found the introduction of aab. Then I follow the instructions in the document. But until I cd to**Obfuscapk/src** on the terminal,Then the following questions were reported: ![image](https://user-images.githubusercontent.com/55529715/221121262-9531831d-675d-47fd-895d-7055b836babf.png) How can I solve it,Looking forward to your reply
**This is my environment variable**
![image](https://user-images.githubusercontent.com/55529715/221121749-762c7582-08b5-43d2-b121-5c81718700f4.png)

**Comment by ClaudiuGeorgiu** [comment]
Hi @TheRangerStar, if you're using `APKTOOL_PATH`, `BUNDLE_DECOMPILER_PATH`, `APKSIGNER_PATH`and `ZIPALIGN_PATH` you have to provide the path to the executable, not the directory containing it. It's a bit different from the classic `PATH` variable where you only specify the directory, sorry for the confusion. So in your case you should set `BUNDLE_DECOMPILER_PATH=/Users/a001/bin/BundleDecompiler.jar` (if that's the name you gave to the jar file).

**Comment by TheRangerStar** [comment]
> Hi @TheRangerStar, if you're using `APKTOOL_PATH`, `BUNDLE_DECOMPILER_PATH`, `APKSIGNER_PATH`and `ZIPALIGN_PATH` you have to provide the path to the executable, not the directory containing it. It's a bit different from the classic `PATH` variable where you only specify the directory, sorry for the confusion. So in your case you should set `BUNDLE_DECOMPILER_PATH=/Users/a001/bin/BundleDecompiler.jar` (if that's the name you gave to the jar file). The same applies to the other variables above: specify the full path of the executable and not the directory containing it.

Ok, I will try it later. Thank you for your reply
