### ISSUE TITLE
ResStringEncryption plugin has not worked correctly

### ISSUE THREAD

**Issue by tnguyenvn** [ClaudiuGeorgiu/Obfuscapk#22]
### Prerequisites

Before opening this issue, I tried the following steps:

- [ OK] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors
- [ OK] Ran the tool using only `Rebuild`, `NewSignature` and `NewAlignment` obfuscators to verify that the app is not using anti-repackaging techniques
- [OK ] Ran the tool using `--ignore-libs` to exclude third party libraries from the obfuscation
- [ OK] Checked that the issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk>

### Description

I have tried "ResStringEncryption" plugin and checked the resource string. The tool did not encrypted the content.

### Steps to Reproduce

1. python3.7 -m obfuscapk.cli -i -o ResStringEncryption  -o Rebuild
2. Decompile APK and check string resource
3. The content is not encrypted as expected

**Expected behavior:**
The resource string/string atrray should be encrpted

**Actual behavior:**
 They are still plain text

```
if applicable, paste here the complete error message
```

### Versions

- **Installation mode** Source
- **Obufscapk version** Lastest
- **OS** (e.g., Ubuntu 16.04): Mac 10.14
- **Python version** (e.g., Python 3.7.4): 3.7.4

### Additional Information

**Apk file(s):**

**Comment by Elyorbe** [comment]
Did you actually use resource string in your source(Java) code? ResStringEncryption uses smali to encrypt the string. If resource string is not used in source code there will be no smali output for resource string, so it will be ignored
