### ISSUE TITLE
How to set path for tools

### ISSUE THREAD

**Issue by Ali-Khazaee** [ClaudiuGeorgiu/Obfuscapk#24]
I've downloaded apktool.jar it's inside src folder also i've jarsinger inside JRE folder but Obfuscapk
does not recognize them, what i have missed ?

**Comment by ClaudiuGeorgiu** [comment]
Hi, you have to install `apktool` as described [here](https://ibotpeaches.github.io/Apktool/install/) and you have to make sure that all the needed executables are in your `PATH` environment variable. Alternatively you can specify the paths by using `APKTOOL_PATH`, `JARSIGNER_PATH` and `ZIPALIGN_PATH` environment variables [as described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#prerequisites-1).

**Comment by NarenderModi** [comment]
Hello developers now tool is public and detected by many virus such as eset.  what extra changes or modification can we do..

so that it   work as new tool works
