### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by Abdulmanan0315** [ClaudiuGeorgiu/Obfuscapk#25]
This is a powerfull obfuscator and works as expected it helped me alot .
This is actually not an issue its Appreciation to you.
Please keep the project running .

Love you

**Comment by packmad** [comment]
You are welcome!
Thank you for your feedback.

**Comment by NarenderModi** [comment]
Hello developers now tool is public and detected by many virus such as eset. what extra changes or modification can we do..

so that it work as new tool works

**Comment by packmad** [comment]
> Hello developers now tool is public and detected by many virus such as eset. what extra changes or modification can we do..
> so that it work as new tool works

I read your comment three times, at midnight, in front of a mirror, and Eugene Kaspersky appeared to me.
