### ISSUE TITLE
Subprocess calls fail on Windows

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#26]
Team Obfuscapk:
I receive numerous errors on _**subprocess.py**_ invocations when trying to run your software on Windows 8. The errors are all of a  _**[WinError 2] The system cannot find the file specified**_ variety,
output capture provided below. Everything is fresh installs.

I believe the error has to do with specifics of Python syntax on Windows platform: Googling for this Error brings a number of links where people discuss how particular Windows syntax needs to be when using subprocess calls. 

Just couple of this:
https://stackoverflow.com/questions/53619765/python-subprocess-filenotfounderror?noredirect=1&lq=1  

> note that writing path with backslashes may be dangerous as you can create escape sequence that way which will be interpreted in different way. You can write windows paths with forward slashes and then call os.path.normpath on them

> .. This was it! Just discovered that my "\bin" was becoming a special character (backspace?) in the final string. Escaping the backslash like so: "\\\bin" throughout the command string fixed the issue

.

https://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call/32799942#32799942

> On Windows, I believe the subprocess module doesn't look in the PATH unless you pass shell=True because it use CreateProcess() behind the scenes

Hopefully these can provide some clues to hep fix it.
Unfortunately my experience with debugging Python is exactly zero, as I lack practical knowledge about how to set up breakpoints/printout arguments on those calls, which would help identify the problem.
Totally open to help if you can guide me on that.

Appreciate you looking into this. Right now I got a feel any Windows user will run into the same issue.

### Output capture 
```
02/05/2020 20:31:08> [ERROR][obfuscapk.tool.Apktool][decode()] Error during decoding: [WinError 2] The system cannot find the file specified
02/05/2020 20:31:08> [ERROR][obfuscapk.obfuscation][decode_apk()] Error during apk decoding: [WinError 2] The system cannot find the file specified
02/05/2020 20:31:08> [ERROR][yapsy_loaded_plugin_Goto_1.goto.Goto][obfuscate()] Error during execution of "Goto" obfuscator: [WinError 2] The system cannot find the file specified
02/05/2020 20:31:08> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\obfuscators\goto\goto.py", line 21, in obfuscate
    for smali_file in util.show_list_progress(obfuscation_info.get_smali_files(),
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\obfuscation.py", line 446, in get_smali_files
    self.decode_apk()
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\cli.py", line 80, in <module>
    perform_obfuscation(arguments.apk_file, arguments.obfuscator, arguments.working_dir, arguments.destination,
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\obfuscators\goto\goto.py", line 21, in obfuscate
    for smali_file in util.show_list_progress(obfuscation_info.get_smali_files(),
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\obfuscation.py", line 446, in get_smali_files
    self.decode_apk()
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\obfuscation.py", line 276, in decode_apk
    apktool.decode(self.apk_path, self._decoded_apk_path, force=True)
  File "C:\Users\myHome\Obfuscapk\src\obfuscapk\tool.py", line 61, in decode
    output = subprocess.check_output(decode_cmd, stderr=subprocess.STDOUT).strip()
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rusty\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified



```

**Comment by ClaudiuGeorgiu** [comment]
Hi, other users reported similar problems on Windows (#7, #11).
The latest commits should however solve the issue since the [tests are passing](https://github.com/ClaudiuGeorgiu/Obfuscapk/actions?query=workflow%3AWindows) and I'm also using it on Windows without problems, so I guess there is a configuration problem.

Please do the following simple test, open a command prompt and type:
```Shell
apktool
```
```Shell
jarsigner
```
```Shell
zipalign
```
Do you get any errors? If you don't get any error then everything *should* work fine, otherwise you should properly install the above tools. You can also specify the location of the needed executables through the following environment variables: `APKTOOL_PATH`, `JARSIGNER_PATH` and `ZIPALIGN_PATH`.

**Comment by skreenr** [comment]
no I run all these w/o problem

    On Monday, May 4, 2020, 6:12:18 AM UTC, Gabriel Claudiu Georgiu <notifications@github.com> wrote:  
 
 


Hi, other users reported similar problems on Windows (#7, #11).
The latest commits should however solve the issue since the tests are passing and I'm also using it on Windows without problems, so I guess there is a configuration problem.

Please do the following simple test, open a command prompt and type:
apktooljarsignerzipalign
Do you get any errors? If you don't get any error then everything should work fine, otherwise you should properly install the above tools. You can also specify the location of the needed executables through the following environment variables: APKTOOL_PATH, JARSIGNER_PATH and ZIPALIGN_PATH.

**Comment by skreenr** [comment]
I don't understand why you saying thisI am reporting you a real problem, and you saying It's not real?

    On Monday, May 4, 2020, 6:12:18 AM UTC, Gabriel Claudiu Georgiu <notifications@github.com> wrote:  
? If you don't get any error then everything should work fine, otherwise you should properly install the above tools. You can also specify the location of the needed executables through the following environment variables: APKTOOL_PATH, JARSIGNER_PATH and ZIPALIGN_PATH.

**Comment by ClaudiuGeorgiu** [comment]
> I am reporting you a real problem, and you saying It's not real?

I never said that, but since I cannot replicate the error on my Windows machine/GitHub Actions, I can only guess what could be the cause of your error. In your logs I see `Python38-32`, are you using a 32 bit system?

**Comment by skreenr** [comment]
No, it's Win8 , 64bitDid I get a wrong Python version?remember you test line is running fine
R- 

    On Monday, May 4, 2020, 7:02:18 AM UTC, Gabriel Claudiu Georgiu <notifications@github.com> wrote:  
 
 



I am reporting you a real problem, and you saying It's not real?


I never said that, but since I cannot replicate the error on my Windows machine/GitHub Actions, I can only guess what could be the cause of your error. In your logs I see Python38-32, are you using a 32 bit system?

**Comment by skreenr** [comment]
It does look like I dwn-loaded 32bit version of python-3.8.2
Checking https://www.python.org/downloads/windows/ I see they have a 64 bit version file named python-3.8.2-amd64.exe  while the one I dwn-loaded was just python-3.8.2.exe
Do you think this would cause the problem?

ThanksR-

**Comment by ClaudiuGeorgiu** [comment]
I made a [quick test using GitHub Actions and the 32 bit version](https://github.com/ClaudiuGeorgiu/Obfuscapk/actions/runs/95029617) and it seems to work fine, so the problem must be somewhere else. Can you write here the output of the command `git log -n1`? I suspect you're not using the latest version of Obfuscapk.

**Comment by skreenr** [comment]
I don't use Git, I dwn-loaded Zip by clicking on the button, then installed from it

    On Monday, May 4, 2020, 8:36:06 AM UTC, Gabriel Claudiu Georgiu <notifications@github.com> wrote:  
 
 


.. Can you write here the output of the command git log -n1? I suspect you're not using the latest version of Obfuscapk.

**Comment by ClaudiuGeorgiu** [comment]
In that case please download again the latest zip as it should contain a fix for the error.

**Comment by skreenr** [comment]
What is the role of these? I haven't done anything with those, instead I had my System Path point to the  package these refer to. 

Thanks,
R -

**Comment by skreenr** [comment]
I see file size is much bigger now, wow!

    On Monday, May 4, 2020, 9:32:37 AM UTC, Gabriel Claudiu Georgiu <notifications@github.com> wrote:  
 
 


In that case please download again the latest zip as it should contain a fix for the error.

**Comment by skreenr** [comment]
It runs silently, and produces a new .apkSince I used Goto module, I expected to see some in the resulting Jva's (I use Jadx to decompile)yet I don't, None! 

Am I missing something?
Thanks,Rusty-

**Comment by skreenr** [comment]
I haven't found anything encrypted using asset_encryption option; 
not video nor any of the drawables' imagesIs it working or I am missing something?
The tool does not make any sort of progress report or status printout, so it's almost like we are guessing if there's any changes there. Some of the plugins make visible changes, others not so much
Thanks,R -

**Comment by ImanCol** [comment]
![image](https://user-images.githubusercontent.com/26169049/89836680-e8dc0a00-db2c-11ea-95c3-0e12c3fbfbc5.png)
![image](https://user-images.githubusercontent.com/26169049/89836691-eed1eb00-db2c-11ea-881c-aa46b07e76f6.png)
![image](https://user-images.githubusercontent.com/26169049/89836713-f5f8f900-db2c-11ea-8ed1-f9ef927b08a4.png)
![image](https://user-images.githubusercontent.com/26169049/89836742-04dfab80-db2d-11ea-9799-6cf897fca57c.png)
![image](https://user-images.githubusercontent.com/26169049/89837523-c3500000-db2e-11ea-98c6-b6629f355f4a.png)
![image](https://user-images.githubusercontent.com/26169049/89837539-ca770e00-db2e-11ea-8133-213eb7124cbd.png)

Work for me
