### ISSUE TITLE
APK won't load

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#27]
Couple of obfuscated APKs that I tried installing on a phone fail to install. 
Install just silently quits w/o any message.
I tried looking at the Manifest files created in working directory, and get a parsing error:
_XML Parsing Error: not well-formed_
Both in the _build_ and _original_ directories; they both are created by APKTool, right?
Any ideas how to trace the problem?
Thanks 

more detail:
Manifest won't show in Explorer at all, and opening withNotepad shows it's full of binary chars along with normal entries. 
Here is first few lines:
  Ü
    ì  2           ä              4   Z      ®   Ò   Þ   ö       (  <  P  ^  p  È  Ì  Þ    F  Z  ž  ¦  Â  Ô  î    $  ^  x  °  Â  ü  *  p  Ž  ž  ö    B  V  Ž  À  ì    R  f  ª  Æ   v e r s i o n C o d e    v e r s i o n N a m e    c o m p i l e S d k V e r s i o n    c o m p i l e S d k V e r s i o n C o d e n a m e   
 m i n S d k V e r s i o n    t a r g e t S d k V e r s i o n    n a m e   
 d e b u g g a b l e

**Comment by ClaudiuGeorgiu** [comment]
If you just decompile the application without performing any obfuscation are you able to open the manifest? What obfuscators are you using? Is there any message in the logcat when you try installing the application?

**Comment by skreenr** [comment]
I tried again with the only option used _-o Rebuild_ 
It fails to load,it just shows on the phone X Not Installed, I  am not using logcat for install

Question: Do I need to use  _-o NewSignature -o NewAlignment_ ?

**Comment by skreenr** [comment]
tried adding -o NewSignature -o NewAlignment , installs now
However the more complex app I tried, out of the two,  won't animate, something is broken
used FieldRename there
