### ISSUE TITLE
NewSignature error

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#28]
I been trying to sign the rebuilt APK with my sig;
For that I replaced the keystore file with mine, however I am getting an Error at signing stage, saying:

_jarsigner.exe returned non-zero exit status 1_

Any experience with those?

**Comment by ClaudiuGeorgiu** [comment]
Have you used the correct password and key alias? Currently this information is hard-coded in the following code, so if you change the keystore you have to also change the password and the key alias.

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/6dcb246ab565c16cdf1e1a721e57583e3221789c/src/obfuscapk/obfuscation.py#L507-L514

**Comment by skreenr** [comment]
Looks like it needs a way to pass a new password;
How can I do that?

**Comment by skreenr** [comment]
I see the part you refer to;
so Which one is the passwd and the alias?

> os.path.dirname(__file__), "resources", "obfuscation_keystore.jks"
>                 ),
>                 "obfuscation_password",
>                 "obfuscation_key",

**Comment by skreenr** [comment]
Looking at this https://docs.oracle.com/javase/tutorial/deployment/jar/signing.html 
and this
https://docs.oracle.com/javase/7/docs/technotes/tools/windows/jarsigner.html#CCHFIDAB
I am having trouble reconciling with your syntax:
their examples only have Alias parameter after the .apk file; yours obviously differs
Please explain.

**Comment by ClaudiuGeorgiu** [comment]
Here is the final code that is executed to sign the application (the above code is only a helper method):

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/6dcb246ab565c16cdf1e1a721e57583e3221789c/src/obfuscapk/tool.py#L207-L221

**Comment by skreenr** [comment]
Seems to be working now, thanks!

**Comment by esauvisky** [comment]
Sorry for bumping a closed issue, but is there any particular reason for the signing to be hardcoded? For me it'd make more sense if you could specify your own keystore, pass and alias from the CLI for example :thinking:

**Comment by ClaudiuGeorgiu** [comment]
Hi @esauvisky, there is no particular reason for having an hardcoded keystore (maybe just to keep the configuration minimal for who is using the tool). We hardcoded it when we started the development since the keystore parameters were always the same, but actually it's a good idea to make this configurable via CLI: I think we should add `--keystore-file`, `--keystore-password` and `--key-alias` optional parameters (and fallback to the default keystore if none of these parameters are provided).

**Comment by skreenr** [comment]
Second that

    On Sunday, May 17, 2020, 7:47:54 AM UTC, Gabriel Claudiu Georgiu <notifications@github.com> wrote:  
 
 


Hi @esauvisky, there is no particular reason for having an hardcoded keystore (maybe just to keep the configuration minimal for who is using the tool). We hardcoded it when we started the development since the keystore parameters were always the same, but actually it's a good idea to make this configurable via CLI: I think we should add --keystore-file, --keystore-password and --key-alias optional parameters (and fallback to the default keystore if none of these parameters are provided).

**Comment by ClaudiuGeorgiu** [comment]
> I think we should add `--keystore-file`, `--keystore-password` and `--key-alias` optional parameters (and fallback to the default keystore if none of these parameters are provided).

Implemented with latest commit 7860fc1a5c9609e9a6e8ffd986221919bd61bd28.
