### ISSUE TITLE
Keep package name intact 

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#29]
I realize now that it's changing package name in the output APK;
How can I revert it back?  or never change it in a first place

**Comment by packmad** [comment]
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/README.md#classrename-rename

**Comment by skreenr** [comment]
I do use ClassRename, I think it is useful. What I need it though is not to mess with the top level Class/package name.
How can this be done?

**Comment by Elyorbe** [comment]
To keep package name unchanged you can change this line 

`self.encrypted_package_name = ".".join( 
         [self.encrypt_identifier(token) for token in self.package_name.split(".")] `

into this line

`self.encrypted_package_name = self.package_name`

in this method

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/c9e493b6b6656f58a46108101432064b93874056/src/obfuscapk/obfuscators/class_rename/class_rename.py#L53-L56

**Comment by vadlike** [comment]
not work
