### ISSUE TITLE
ofuscar los .xml

### ISSUE THREAD

**Issue by demianrey** [ClaudiuGeorgiu/Obfuscapk#31]
Hola, bueno antes que nada agradezco su gran trabajo en esta herramienta...
Bueno mi pregunta es si puedo ofuscar los archivos .xml ya que probé varios métodos y en ninguno cambio el código (hacerlo incomprensible)

Saludos

**Comment by ClaudiuGeorgiu** [comment]
Please use English, otherwise I won't be able to help.
