### ISSUE TITLE
Question on Multiple Obfuscation Runs

### ISSUE THREAD

**Issue by justinagain** [ClaudiuGeorgiu/Obfuscapk#33]
Hi Obfuscapk Team,

I have a question about multiple obfuscations of the same APK.  Here goes:

1. I have an APK and I obfuscate it using one obfuscator - Reflection.
2. It works fine and I end up with an obfuscated APK.
3. I then take that obfuscated APK and run it again through Obfuscapk - using the Reflection obfuscator.    My goal is to understand if more reflection will be added  - or if you get the most possible via the first run.
4.  What happens is that it fails with the error below.  Seems like its main issue is:

Could not smali file: com/apireflectionmanager/ApiReflection.smali

I get that it introduces com.apireflectionmanager.ApiReflection.java as part of the first pass.  Looks like a second pass would not be possible.  Just confirming.  Also - if it were possible - do you think more reflection would be introduced?

ERROR OUPUT
```
import 'yapsy_loaded_plugin_ConstStringEncryption_1.const_string_encryption' # <_frozen_importlib_external.SourceFileLoader object at 0x7fe300ac5950>
import 'yapsy_loaded_plugin_ConstStringEncryption_1' # <_frozen_importlib_external.SourceFileLoader object at 0x7fe300ac5650>
# /projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/debug_removal/__pycache__/__init__.cpython-37.pyc matches /projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/debug_removal/__init__.py
# code object from '/projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/debug_removal/__pycache__/__init__.cpython-37.pyc'
# /projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/debug_removal/__pycache__/debug_removal.cpython-37.pyc matches /projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/debug_removal/debug_removal.py
# code object from '/projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/debug_removal/__pycache__/debug_removal.cpython-37.pyc'
import 'yapsy_loaded_plugin_DebugRemoval_1.debug_removal' # <_frozen_importlib_external.SourceFileLoader object at 0x7fe300ac5ed0>
import 'yapsy_loaded_plugin_DebugRemoval_1' # <_frozen_importlib_external.SourceFileLoader object at 0x7fe300ac5b90>
04/06/2020 14:22:08> [ERROR][obfuscapk.tool.Apktool][build()] Error during build command: I: Using Apktool 2.4.0
I: Smaling smali folder into classes.dex...
../../../../../../../../gpfs/scratch/jmdv/junk4/StockTicker_obfuscated/smali/com/apireflectionmanager/ApiReflection.smali[11,12] Class Lcom/apireflectionmanager/ApiReflection; has already been interned
Could not smali file: com/apireflectionmanager/ApiReflection.smali

04/06/2020 14:22:08> [ERROR][obfuscapk.obfuscation][build_obfuscated_apk()] Error during apk building: Command '['apktool', 'b', '--force-all', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated', '-o', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated_obfuscated.apk']' returned non-zero exit status 1.
04/06/2020 14:22:08> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: Command '['apktool', 'b', '--force-all', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated', '-o', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated_obfuscated.apk']' returned non-zero exit status 1.
04/06/2020 14:22:08> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: Command '['apktool', 'b', '--force-all', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated', '-o', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated_obfuscated.apk']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/main.py", line 88, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/obfuscation.py", line 396, in build_obfuscated_apk
    apktool.build(self._decoded_apk_path, self.obfuscated_apk_path)
  File "/projects/academic/stevko/delvecchio/obfuscation/obfuscapk/Obfuscapk/src/obfuscapk/tool.py", line 93, in build
    output = subprocess.check_output(build_cmd, stderr=subprocess.STDOUT).strip()
  File "/util/common/python/py37/anaconda-2020.02/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/util/common/python/py37/anaconda-2020.02/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apktool', 'b', '--force-all', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated', '-o', '/gpfs/scratch/jmdv/junk4/StockTicker_obfuscated_obfuscated.apk']' returned non-zero exit status 1.
```

**Comment by ClaudiuGeorgiu** [comment]
Hi @justinagain, I didn't consider the scenario where an user would obfuscate the same app multiple times. As you pointed out, the error is caused by `com/apireflectionmanager/ApiReflection.smali`: on the second run the tool tries to include this file that is already there from the first run.

When using reflection obfuscator, you cannot just ignore or replace `com/apireflectionmanager/ApiReflection.smali` because it contains information about the actual methods to use with reflection, so you would need to "merge" all `com/apireflectionmanager/ApiReflection.smali` files for all the runs or to use a different name for this class (not only in this file but also all the invocations). Similar considerations are also valid for the encryption obfuscator.

Does this operation add "more obfuscation"? It depends. Most of the obfuscation techniques implemented in Obfuscapk add new methods/variables to the code. There is a [64k limit](https://developer.android.com/studio/build/multidex#about) that is very easy to reach in real applications and when applying multiple obfuscators. If such limit is reached on the first run, subsequent runs would be useless because there is no space left to add new stuff. However, if the limit is not reached on the first run, I guess you could run the same obfuscator multiple times (but as I said before, I haven't tested this scenario).

**Comment by justinagain** [comment]
Thanks for this reply - it is perfect.  I will be trying multiple runs of obfuscation on a few other obfuscators - letting you know how it turn out.

**Comment by xawlo** [comment]
> Привет @justinagain, я не рассматривал сценарий, когда пользователь будет запутывать одно и то же приложение несколько раз. Как вы уже отмечали, ошибка вызвана `com/apireflectionmanager/ApiReflection.smali`тем, что при втором запуске инструмент пытается включить этот файл, который уже существует с первого запуска.
> 
> При использовании Reflection obfuscator вы не можете просто игнорировать или заменять `com/apireflectionmanager/ApiReflection.smali`его, потому что он содержит информацию о фактических методах, используемых с reflection, поэтому вам нужно будет "объединить" все `com/apireflectionmanager/ApiReflection.smali`файлы для всех запусков или использовать другое имя для этого класса (не только в этом файле, но и во всех вызовах). Аналогичные соображения справедливы и для обфускатора шифрования.
> 
> Добавляет ли эта операция "еще больше запутанности"? Это зависит. Большинство методов обфускации, реализованных в Obfuscapk, добавляют в код новые методы/переменные. Существует [предел 64k](https://developer.android.com/studio/build/multidex#about), который очень легко достичь в реальных приложениях и при применении нескольких обфускаторов. Если такой предел достигается при первом запуске, последующие запуски будут бесполезны, потому что не останется места для добавления новых материалов. Однако, если предел не будет достигнут при первом запуске, я думаю, что вы можете запустить один и тот же обфускатор несколько раз (но, как я уже говорил, я не тестировал этот сценарий).

And if at the first start the limit of 64K is reached even when using a pair of encryption methods, and the process crashes with an error, is it possible to circumvent this somehow?

**Comment by xawlo** [comment]
> Hi @justinagain, I didn't consider the scenario where an user would obfuscate the same app multiple times. As you pointed out, the error is caused by `com/apireflectionmanager/ApiReflection.smali`: on the second run the tool tries to include this file that is already there from the first run.
> 
> When using reflection obfuscator, you cannot just ignore or replace `com/apireflectionmanager/ApiReflection.smali` because it contains information about the actual methods to use with reflection, so you would need to "merge" all `com/apireflectionmanager/ApiReflection.smali` files for all the runs or to use a different name for this class (not only in this file but also all the invocations). Similar considerations are also valid for the encryption obfuscator.
> 
> Does this operation add "more obfuscation"? It depends. Most of the obfuscation techniques implemented in Obfuscapk add new methods/variables to the code. There is a [64k limit](https://developer.android.com/studio/build/multidex#about) that is very easy to reach in real applications and when applying multiple obfuscators. If such limit is reached on the first run, subsequent runs would be useless because there is no space left to add new stuff. However, if the limit is not reached on the first run, I guess you could run the same obfuscator multiple times (but as I said before, I haven't tested this scenario).

And if at the first start the limit of 64K is reached even when using a pair of encryption methods, and the process crashes with an error, is it possible to circumvent this somehow?
