### ISSUE TITLE
does it support kotlin?

### ISSUE THREAD

**Issue by amirreza-sobhdel** [ClaudiuGeorgiu/Obfuscapk#34]
I know it tries to obfuscate smali code and probably it doesn't matter if the source code is in java or kotlin but i get this error after obfuscating kotlin which leads to crashing!

**java.lang.VerifyError: Verifier rejected class kotlin.text.StringsKt__StringsKt: kotlin.sequences.Sequence kotlin.text.StringsKt__StringsKt.lineSequence(java.lang.CharSequence) failed to verify: kotlin.sequences.Sequence kotlin.text.StringsKt__StringsKt.lineSequence(java.lang.CharSequence): [0x17] copyRes1 v4<- result0 type=Undefined (declaration of 'kotlin.text.StringsKt__StringsKt' appears in /data/app/com.willowdev.jniexample-y8XwLqPySLWXJYecEY6H0A==/base.apk)
        at kotlin.text.StringsKt__StringsKt.removePrefix(Unknown Source:0)**

**Comment by ClaudiuGeorgiu** [comment]
Hi, I didn't do any specific tests for Kotlin, thanks for reporting. Can you provide more information (at least the used obfuscators)? Thanks.

**Comment by sickoxyz** [comment]
this is work or not in kotlin bro?
