### ISSUE TITLE
No output of obfuscated APK?

### ISSUE THREAD

**Issue by frestoinc** [ClaudiuGeorgiu/Obfuscapk#35]
### Prerequisites

Before opening this issue, I tried the following steps:

* [x] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors

* [x] Ran the tool using only `Rebuild`, `NewSignature` and `NewAlignment` obfuscators to verify that the app is not using anti-repackaging techniques

* [x] Ran the tool using `--ignore-libs` flag to exclude third party libraries from the obfuscation

* [x] Checked [FAQ](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/FAQ.md) and [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/TROUBLESHOOTING.md)

* [x] Checked for [existing similar issues on GitHub](https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk)

### Description

No output when running the script

### Steps to reproduce

1.  Obfuscapk\src>py -m obfuscapk.cli -p -o Rebuild test.apk
2. 
3. 

**Expected behavior:**

output apk should be shown in obfuscation_working_dir

**Actual behavior:**
only files such as assets, res, manifest etc can be found. no sign of apk

No error. everything is successful.
Running obfuscators (Rebuild): 100%|██████████████████████████████████████████████████|[01:22<00:00, 82.57s/obfuscator]

### Versions

- **Installation mode** (e.g., from source or with Docker):
source
- **Obufscapk version** (e.g., commit 0676488):
commit 75cbc4e
- **OS** (e.g., Ubuntu 16.04):
Windows 10
- **Python version** (e.g., 3.7.4):
3.7.3
- **Apktool version** (e.g., v2.4.0):
2.4.1

### Additional information

**Apk file(s):**

**Comment by ClaudiuGeorgiu** [comment]
Hi, sorry but I cannot replicate. If I run `python3 -m obfuscapk.cli -p -o Rebuild test.apk` the obfuscated application is generated in `obfuscation_working_dir/test_obfuscated.apk` while all the other files (resources, assets etc.) are in the directory `obfuscation_working_dir/test/` (I'm testing on Windows 10). You can try adding the option `-d destination.apk` to specify where the obfuscated application should be saved.

**Comment by frestoinc** [comment]
i believe it has something to do with the apk size? Previously i'm using a 70MB apk earlier which was not generating output apk. Tried again with a smaller size (5MB) and the output is in `obfuscation_working_dir/`

**Comment by ardalan-foroughi** [comment]
I am facing the same issue. The command `python3 -m obfuscapk.cli -p -d ~/result.apk -o Nop ~/app-debug.apk` works fine and shows progress finishes normally but there is no output. I have tried it in both linux and windows systems with a couple of apps and none of them works. there is no result in `~/` or `obfuscation_working_dir/ ` directories.

**Comment by ClaudiuGeorgiu** [comment]
Hi @ardalan-foroughi, you need to use at least `Rebuild` obfuscator, otherwise the obfuscated apk won't be created.
