### ISSUE TITLE
Add option for "--use-aapt2" when build with apktool

### ISSUE THREAD

**Issue by yfyau** [ClaudiuGeorgiu/Obfuscapk#37]
### Is this feature request related to a problem?

Yes, I was facing an error when build the new apk. And I found this:
https://github.com/iBotPeaches/Apktool/issues/1978

### Proposed solution

I manually change the code in tool.py
build_cmd: List[str] = [self.apktool_path, "b", "--force-all", source_dir_path]
to
build_cmd: List[str] = [self.apktool_path, "b", "--force-all", "--use-aapt2", source_dir_path]

However, I think it will be better to add an option to toggle.

### Additional context

Noooo

### Would you like to submit a pull request for this feature?

I am lazy :P

Btw, Nice work! Hope more people can enjoy this in future. Star is a must!

**Comment by ClaudiuGeorgiu** [comment]
Hi, thanks for the feature request. The need of `--use-aapt2` flag was also reported in #23, so I guess it's time to include it as an option in the next release.

**Comment by GamesDean** [comment]
> Hi, thanks for the feature request. The need of `--use-aapt2` flag was also reported in #23, so I guess it's time to include it as an option in the next release.

Any update about this issue? I am facing the same problem. Anyway thank you, this tool rocks

**Comment by ClaudiuGeorgiu** [comment]
Added in #84.
