### ISSUE TITLE
Request more Resource Obfuscate

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#38]
Hi, 
Nowadays, i saw many app have steal resources like drawables, animations, layout from another app then modify and make it for themself. I think Resource Obfuscate is very best to prevent this situation.
Currently Obfusapk have only 1 Resource Obfuscate type "RandomManifest", i think it will need more type to make stronger obfuscate like:
- XML Layouts
- XML Values
- Drawables
- Animations
- Menus

Every type above can use tech like Encrypt - Rename - ReOrder - Insert Junk to make it unique and obfuscated.

**Comment by packmad** [comment]
I've been thinking a lot about the obfuscation of the resources. The problem is that it is not trivial... I have some ideas, but I'm not satisfied.
But I can assure you that (when we have time) this will be the next feature of Obfuscapk.

**Comment by tracer8** [comment]
Thank you for listening!
