### ISSUE TITLE
Can i use NonAsii characters for rename?

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#43]
Hi, 
I tried to use NonAsii character for rename to use some chinese character like "其道能面将方都生用",  but it always trigger error on print method:
`UnicodeEncodeError: 'charmap' codec can't encode characters`
Then i tried to uncoment all print method, it is build success, but check on decompile tool, it's not Nonasii characters i'm looking for.
Did i miss somethings?

Here is simple code to generate non asii chars, i have test on simple project, it's print success, but on Obfuscator src, it always trigger "UnicodeEncodeError" .

```
nonasiiChars = "对在后分子中的只无这同么有也好此公又定不而所人年其道能面将方都生用种心你"
asiiChars ="abcdefghijklmnopqrstuvwxyz0123456789"
dictChars = {}


def HandleDictChars():
    for id, item in enumerate(asiiChars):
        dictChars[item] = nonasiiChars[id]
    print(dictChars)
	
def GenerateRandomNameNonasii():
    input_string = "akjfadslfjsadlj234234"
    md5String = md5(input_string.encode()).hexdigest()
    result = md5String
    for key, value in dictChars.items():
        result = result.replace(key, value)

    print("md5String: " + md5String)
    print("Result: " + result)

HandleDictChars()
GenerateRandomNameNonasii()
```

Here is decompile code after use NonAsii characters:
![PicPick_060](https://user-images.githubusercontent.com/15725821/86923653-86bc6d80-c158-11ea-965b-906081979b1a.jpg)

**Comment by ClaudiuGeorgiu** [comment]
I'm able to replicate the problem, thanks for reporting. This can be solved, but some refactoring is needed.

**Comment by tracer8** [comment]
Thank you!

**Comment by ClaudiuGeorgiu** [comment]
Hi @tracer8, the latest commit c9e493b6b6656f58a46108101432064b93874056 should fix the issue with non ascii characters.

**Comment by tracer8** [comment]
Thank you! I will checking it.
