### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by ZSSST** [ClaudiuGeorgiu/Obfuscapk#45]
hello,myfriend
when i use  -o OBFUSCATOR
they often report this error：

Command '['G:\\android tool\\ApkToolBox_v1.6.4\\tool\\apktool\\apktool.BAT', 'd', '--force', '1.apk', '-o', 'obfuscation_working_dir\\1']' returned non-zero exit status 1.

is there anything wrong with my apktool？

**Comment by ZSSST** [comment]
my apktool version is 2.3.3

**Comment by packmad** [comment]
Update apktool, the Current Version is 2.4.1. 
Use directly apktool on that apk bypassing Obfuscapk. Decompile and rebuild. 
If apktool fails, it is not a problem of Obfuscapk.
