### ISSUE TITLE
Problem with a "NewAlignment"

### ISSUE THREAD

**Issue by ShemyakinAV** [ClaudiuGeorgiu/Obfuscapk#48]
Hello there! I tryed use your obfuscator, but I receive some problem. I run configuration 
"python -m obfuscapk.cli -i -p -o RandomManifest -o ArithmeticBranch -o AdvancedReflection -o Reflection -o FieldRename -o ConstStringEncryption -o ResStringEncryption -o DebugRemoval -o Goto -o Rebuild -o Reorder -o NewSignature -o NewAlignment 1.apk"
After some minutes i look at process and I found that the process is frozen! Just at the moment "NewAlignment".W
![problem](https://user-images.githubusercontent.com/17363905/89458247-64c20500-d76f-11ea-8b1c-a7771554ca3e.png)
aiting didn't help me :(
What might be the problem?

**Comment by ClaudiuGeorgiu** [comment]
Hi, have you seen the [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/TROUBLESHOOTING.md)? Is `zipalign` installed correctly?

**Comment by ShemyakinAV** [comment]
> 
> 
> Hi, have you seen the [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/TROUBLESHOOTING.md)? Is `zipalign` installed correctly?

If I write in cmd only "zipalign" - check attached first pic
If I write path like "sdk/buildtools/" and write zipalign - check attached second pic

It looks like a problem with a java runtime version, do you know how I can repair it?
![p1](https://user-images.githubusercontent.com/17363905/89522149-6b8d5e00-d7e9-11ea-8ecb-73459904b56c.png)
![p2](https://user-images.githubusercontent.com/17363905/89522153-6cbe8b00-d7e9-11ea-9fbe-490532ade3b0.png)

**Comment by ClaudiuGeorgiu** [comment]
You have to use the [`zipalign`](https://developer.android.com/studio/command-line/zipalign) binary that comes with Android SDK, none of your screenshots are using the correct binary.

**Comment by ImanCol** [comment]
Opfiscapk?
