### ISSUE TITLE
Obfuscate Ionic apk

### ISSUE THREAD

**Issue by suarezgl** [ClaudiuGeorgiu/Obfuscapk#49]
Hi, I trying used this tool for obfuscate ionic app (.apk) in multiple attempts with differences Obfuscator but the result its the same, apk never is installed. 

I using docker mode.

any recommendation for my case?

**Comment by ClaudiuGeorgiu** [comment]
Hi @suarezgl, this tool was not tested with hybrid apps, but i might be an interesting enhancement.
