### ISSUE TITLE
GoTo Implementation

### ISSUE THREAD

**Issue by justinagain** [ClaudiuGeorgiu/Obfuscapk#52]
This is a general question about the GoTo obfuscation.  I understand what it does, adding the two new nodes at the beginning and end of methods.  I have a couple questions:

1. Have you considered a more complex application of goto?  That is, adding gotos within the body of the methods themselves.  My guess is you would need to understand the control flow of the method from beginning to end and then calculate where and how an acceptable goto may be introduced.  Which would require a complex algorithm and really 
difficult to introduce in looping constructs.

2. Second, the goto introduced is at the byte code level.  So, I just wanted to verify that its not problematic to introduce a goto into the method body as part of the obfuscation process.  I would think there is no reason it would be a problem but wanted to double check.

Thanks!

Justin

**Comment by ClaudiuGeorgiu** [comment]
Hi @justinagain, for 1) look at [Reorder](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/master/src/obfuscapk/obfuscators/reorder) obfuscator, it should do something similar to what you described. For 2), since both Goto and Reorder obfuscators _usually_ work, I think goto instructions can be used inside the body of a method without problems.

**Comment by justinagain** [comment]
@ClaudiuGeorgiu  - thanks for this.  So, I ran Reorder and indeed it added random gotos.  Now the fun part - this causes many problems for decompilation.  Neither of these are Obfuscapk's problem, per se, but something people should be aware of.

1.) A tool like Jadx that uses smali will fail on those methods and be unable to create Java source code.  As there is no unconditional goto in Java (but there is in Dalvik byte code) - it cannot render the obfuscated code back to Java.  Jadx will output the byte code so you at least know what is going on.
2.) More problematic is running this through a tool like Soot.  Soot will fail on these and outline an error related to the Registy and null pointer.  I do not know the ramifications of this.  It's possible that Soot is unable to handle the unconditional goto or maybe its an invalid app output by Obfuscapk.  I did not run it in an emulator to see which is the case - have no plans to.  Just letting you know!

You can close this ticket.

**Comment by ClaudiuGeorgiu** [comment]
Thanks for the feedback!
