### ISSUE TITLE
MethodRename not working?

### ISSUE THREAD

**Issue by xawlo** [ClaudiuGeorgiu/Obfuscapk#53]
Hello, i wrote a simple code to see how renaming works
![photo_2020-08-18_16-13-56](https://user-images.githubusercontent.com/26900368/90495311-a8a10b00-e16e-11ea-8f04-ebe605fd9219.jpg)
Collected apk file and launched obfuscation with the following parameters
![photo_2020-08-18_16-16-49](https://user-images.githubusercontent.com/26900368/90495634-09c8de80-e16f-11ea-8e72-dada18618dd9.jpg)
as for renaming fields, it worked well. But with renaming methods, something is wrong
![photo_2020-08-18_16-18-12](https://user-images.githubusercontent.com/26900368/90495933-63310d80-e16f-11ea-87e0-687d50ae4476.jpg)

**Comment by ClaudiuGeorgiu** [comment]
Hi @xawlo, please see https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/42#issuecomment-655396643, it explains why method renaming is not working in your case.
