### ISSUE TITLE
Apktool build fail

### ISSUE THREAD

**Issue by ardalanForoughipour** [ClaudiuGeorgiu/Obfuscapk#54]
I was trying Obfuscapk on a sample application and I got this error.

```
subprocess.CalledProcessError: Command '['/usr/bin/apktool', 'b', '--force-all', '/home/ardalan/obfuscation_working_dir/app-release', '-o', '/home/ardalan/result.apk']' returned non-zero exit status 1.
Running obfuscators (Rebuild):  50%|█████████████████████████▌                         |[00:03<00:03,  3.89s/obfuscator]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ardalan/Obfuscapk/src/obfuscapk/cli.py", line 177, in <module>
    main()
  File "/home/ardalan/Obfuscapk/src/obfuscapk/cli.py", line 172, in main
    arguments.key_password,
  File "/home/ardalan/Obfuscapk/src/obfuscapk/main.py", line 144, in perform_obfuscation
    (obfuscator_name_to_function[obfuscator_name])(obfuscation)
  File "/home/ardalan/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate
    obfuscation_info.build_obfuscated_apk()
  File "/home/ardalan/Obfuscapk/src/obfuscapk/obfuscation.py", line 502, in build_obfuscated_apk
    apktool.build(self._decoded_apk_path, self.obfuscated_apk_path)
  File "/home/ardalan/Obfuscapk/src/obfuscapk/tool.py", line 158, in build
    build_cmd, stderr=subprocess.STDOUT, input=b"\n"
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/apktool', 'b', '--force-all', '/home/ardalan/obfuscation_working_dir/app-release', '-o', '/home/ardalan/result.apk']' returned non-zero exit status 1.
```

after some debugging I found out this is because of Apktool trying to reconstruct resourses from the decoded files of an app which have not been successfully decoded. I fixed this issue by modifying tool.py file and adding the "-r" to the "decode_cmd" list when calling Apktool.

I was wondering if in the new version there would flag that would automatically add "-r" in apktook command. 
Although Obfuscapk does resource obfuscation and adding "-r"  may cause problems for them, for other types of obfuscation this flag will mitigate some crashes.

**Comment by Drzeww** [comment]
Could you please explain more? Where did you add it and how?

I got same issue.

**Comment by ardalan-foroughi** [comment]
> Could you please explain more? Where did you add it and how?
> 
> I got same issue.

 this is a problem of apktool with resources and since I don't care about resources I added the  '-r' in the Obfuscapk/src/obfuscapk/tool.py at line 88 before '-o' parameter to indicate apktool should ignore resources.

**Comment by Drzeww** [comment]
decode_cmd: List[str] = [
            self.apktool_path,
            "d",
            apk_path,
            "-r"  "-o" ,
            output_dir_path,
            
        ]



Even with that i am getting same error ;/
My call : 
python3 -m obfuscapk.cli -p -w /home/kali/Desktop/working-dir/ -o ConstStringEncryption -o Goto -o Nop -o LibEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o ConstStringEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o Rebuild -o NewSignature -o NewAlignment -d /home/kali/Desktop/apphot.apk '/home/kali/Desktop/app.apk'

**Comment by Drzeww** [comment]
`python3 -m obfuscapk.cli -p -w /home/kali/Desktop/working-dir/ -o ConstStringEncryption -o Goto -o Nop -o LibEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o ConstStringEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o Rebuild -o NewSignature -o NewAlignment -d /home/kali/Desktop/apphot.apk '/home/kali/Desktop/app.apk' `

**Comment by Drzeww** [comment]
``python3 -m obfuscapk.cli -p -w /home/kali/Desktop/working-dir/ -o ConstStringEncryption -o Goto -o Nop -o LibEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o ConstStringEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o Rebuild -o NewSignature -o NewAlignment -d /home/kali/Desktop/apphot.apk '/home/kali/Desktop/app.apk'

**Comment by ctwoon** [comment]
> `decode_cmd: List[str] = [
> self.apktool_path,
> "d",
> apk_path,
> "-r" "-o" ,
> output_dir_path,
> 
> ```
>     ]`
> ```
> 
> Even with that i am getting same error ;/
> My call :
> 
> `python3 -m obfuscapk.cli -p -w /home/kali/Desktop/working-dir/ -o ConstStringEncryption -o Goto -o Nop -o LibEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o ConstStringEncryption -o ResStringEncryption -o RandomManifest -o AssetEncryption -o ConstStringEncryption -o ClassRename -o FieldRename -o MethodRename -o Rebuild -o NewSignature -o NewAlignment -d /home/kali/Desktop/apphot.apk '/home/kali/Desktop/app.apk' `

firstly, it should be like
