### ISSUE TITLE
RuntimeError: Something is wrong with executable "/usr/share/apktool" (GNU/Linux)

### ISSUE THREAD

**Issue by All-io-X-oi-llA** [ClaudiuGeorgiu/Obfuscapk#56]
### Prerequisites

Before opening this issue, I tried the following steps:

* [x] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors

* [ ] Ran the tool using only `Rebuild`, `NewSignature` and `NewAlignment` obfuscators to verify that the app is not using anti-repackaging techniques

* [ ] Ran the tool using `--ignore-libs` flag to exclude third party libraries from the obfuscation

* [x] Checked [FAQ](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/FAQ.md) and [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/TROUBLESHOOTING.md)

* [x] Checked for [existing similar issues on GitHub](https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk)

### Description
unable to find why or what is causing this error.

```
┌─[root@parrot-sec]─[/home/USER/Obfuscapk/src]
└──╼ #python3 -m obfuscapk.cli -p -w /home/USER/temp working dir/ -d /home/USER/obfuscated.apk -o ConstStringEncryption -o Nop -o Goto -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment /home/USER/Obf testing.apk

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/USER/Obfuscapk/src/obfuscapk/cli.py", line 177, in <module>
    main()
  File "/home/USER/Obfuscapk/src/obfuscapk/cli.py", line 131, in main
    check_external_tool_dependencies()
  File "/home/USER/Obfuscapk/src/obfuscapk/main.py", line 40, in check_external_tool_dependencies
    Apktool()
  File "/home/USER/Obfuscapk/src/obfuscapk/tool.py", line 28, in __init__
    raise RuntimeError(
RuntimeError: Something is wrong with executable "/usr/share/apktool"
```

### Versions

- **Installation mode** (e.g., from source or with Docker): from source
- **Obufscapk version** (e.g., commit 0676488): Obfuscapk 1.2.0
- **OS** (e.g., Ubuntu 16.04): Parrot OS Security v4.10
- **Python version** (e.g., 3.7.4): Python 3.8.5
- **Apktool version** (e.g., v2.4.0): Apktool v2.4.1-dirty

**Comment by ClaudiuGeorgiu** [comment]
Hi, are you able to use `apktool` without Obfuscapk? If you just execute `apktool` in a terminal, does it work correctly? What if you try executing `/usr/share/apktool`?

**Comment by All-io-X-oi-llA** [comment]
Yes i'm able to use `apktool` without Obfuscapk, 
yes apktool is working correctly 
```
$apktool
Apktool v2.4.1-dirty - a tool for reengineering Android apk files
with smali v2.4.0-debian and baksmali v2.4.0-debian
Copyright 2014 Ryszard Wiśniewski <brut.alll@gmail.com>
Updated by Connor Tumbleson <connor.tumbleson@gmail.com>

usage: apktool ....

```
What if you try executing `/usr/share/apktool`?
it outputs `bash: /usr/share/apktool: Is a directory`

Additional info:
I tried `/usr/share/apktool`because i found this in the code of `/usr/bin/apktool` main executable file for running `Apktool`.
I also tried with `export APKTOOL_PATH=/usr/bin/apktool` but with this config i get 

```
usage: python3 -m obfuscapk.cli [-h] -o OBFUSCATOR [-w DIR] [-d OUT_APK] [-i]
                                [-p] [-k VT_API_KEY]
                                [--keystore-file KEYSTORE_FILE]
                                [--keystore-password KEYSTORE_PASSWORD]
                                [--key-alias KEY_ALIAS]
                                [--key-password KEY_PASSWORD]
                                <APK_FILE>
python3 -m obfuscapk.cli: error: unrecognized arguments: dir/ /home/USER/Obf testing.apk
```
```

**Comment by ClaudiuGeorgiu** [comment]
> I tried `/usr/share/apktool`because i found this in the code of `/usr/bin/apktool` main executable file for running `Apktool`.
> I also tried with `export APKTOOL_PATH=/usr/bin/apktool` but with this config i get

Ok, so for some reason Obfuscapk was not getting the correct `apktool` path, but setting the correct path fixes the issue. The last error is caused by the spaces in the path: if you have paths with spaces, you have to use quotes (e.g., `"/home/USER/temp working dir/"` and `"/home/USER/Obf testing.apk"`).

**Comment by All-io-X-oi-llA** [comment]
still getting error
![2020-09-17_20-35](https://user-images.githubusercontent.com/67152461/93490246-c42b3d00-f8f7-11ea-945d-440e546d77f7.png)

apktool is working fine
![2020-09-17_20-38](https://user-images.githubusercontent.com/67152461/93490298-d5744980-f8f7-11ea-9221-0973f7a1f24a.png)

**Comment by ClaudiuGeorgiu** [comment]
Well, you have to use quotes for all the paths containing spaces, not only for the last path.

**Comment by All-io-X-oi-llA** [comment]
Thank you for your help.
(my mistake)
