### ISSUE TITLE
Encryption example missing, surely needed

### ISSUE THREAD

**Issue by skreenr** [ClaudiuGeorgiu/Obfuscapk#57]
Would be great if anyone can share actual example/use case of the Encryption.
Myself I was not able to figure out how to use it, perhaps I was "holding it the wrong way" to paraphrase someone

**Comment by ClaudiuGeorgiu** [comment]
Hi, you can start by looking at [asset encryption example](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/c9e493b6b6656f58a46108101432064b93874056/src/obfuscapk/obfuscators/asset_encryption/example), [lib encryption example](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/c9e493b6b6656f58a46108101432064b93874056/src/obfuscapk/obfuscators/lib_encryption/example) and a [simple test application](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/c9e493b6b6656f58a46108101432064b93874056/src/test/test_resources/v1.0).
