### ISSUE TITLE
Any plan for Android App Bundles?

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#59]
Hi,
As Google said:
`In the second half of 2021, new apps will be required to publish with the Android App Bundle on Google Play. New apps larger than 150MB will have to use either dynamic feature delivery or dynamic asset delivery.` - [Source](https://support.google.com/googleplay/android-developer/answer/9006925?hl=en)

Obfusapk work only on .apk file, so did you have any plan to upgrade this tool for  Android App Bundles(AAB) file?

**Comment by ClaudiuGeorgiu** [comment]
Hi, currently we don't have any roadmap for bundle support (see #6).
