### ISSUE TITLE
Bundle Support

### ISSUE THREAD

**Issue by eakteam** [ClaudiuGeorgiu/Obfuscapk#6]
Will it support Android Application Bundle (.aab) in the following ?

**Comment by packmad** [comment]
At the moment this project relies heavily on smali files and uses Apktool to decompile and rebuild the app.
We need time to study [bundletool](https://github.com/google/bundletool) and if we can easily integrate it in Obfuscapk... for sure!

**Comment by eakteam** [comment]
Thanks for your response.... Will wait for it and it will be great since everyone is migrating to bundle in those days.

**Comment by packmad** [comment]
BTW any contribution to Obfuscapk is welcome :)

**Comment by qb20nh** [comment]
https://github.com/TamilanPeriyasamy/BundleDecompiler

**Comment by ClaudiuGeorgiu** [comment]
Initial support for app bundles added by #121.
