### ISSUE TITLE
Method Rename + ignore known third party libraries bug

### ISSUE THREAD

**Issue by kiber-io** [ClaudiuGeorgiu/Obfuscapk#60]
Hi!
Sorry for my English, i'm Russian :D
So, bug:

1. Turn on ignore known third party libraries (key -i)
2. Turn on Method Rename
3. Get an error when launching the app
`java.lang.NoSuchMethodError: No static method ma597a055(III)I in class Landroidx/core/math/MathUtils; or its super classes (declaration of 'androidx.core.math.MathUtils' appears in base.apk)`
Why? Because the class `androidx.core.math.MathUtils` has method `clamp(III)I`, the call that the obfuscator processed and as a result, we have a call of this type
`invoke-static {p2, p1, p3}, Landroidx/core/math/MathUtils;->ma597a055(III)I`
instead of 
`invoke-static {p2, p1, p3}, Landroidx/core/math/MathUtils;->clamp(III)I`

**Comment by ClaudiuGeorgiu** [comment]
Hi, can you provide the original apk file? It will be easier to investigate the error, thanks.

**Comment by kiber-io** [comment]
Of course

[Kate66.zip](https://github.com/ClaudiuGeorgiu/Obfuscapk/files/5421543/Kate66.zip)

**Comment by ClaudiuGeorgiu** [comment]
Thanks, I'm able to replicate the issue (only statically, since I don't have an account to test the app past the login screen). I will try to find a solution when I have time, thanks for the report.

**Comment by kiber-io** [comment]
Here's how I solved the problem

**..\Obfuscapk\src\obfuscapk\obfuscators\method_rename\method_rename.py**
```
def obfuscate(self, obfuscation_info: Obfuscation):
    ......
    self.rename_method_invocations(
        obfuscation_info.get_smali_files(),
        renamed_methods,
        android_class_names,
        util.get_libs_to_ignore(), # <--- add parameter
        obfuscation_info.interactive
    )
```
```
def rename_method_invocations(
    self,
    smali_files: List[str],
    methods_to_rename: Set[str],
    android_class_names: Set[str],
    classes_to_ignore: List[str], # <--- add parameter
    interactive: bool = False,
):
    ......
    if (
        ("direct" in invoke_type or "static" in invoke_type)
        and method in methods_to_rename
        and class_name not in android_class_names
        and not any(cls in class_name for cls in classes_to_ignore) # <--- add a condition
    ):
```
