### ISSUE TITLE
apktool error: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):

### ISSUE THREAD

**Issue by Coroline** [ClaudiuGeorgiu/Obfuscapk#64]
I encountered an error when running the command: "**python3 -m obfuscapk.cli -p -w E:\test -d E:\out.apk -o ConstStringEncryption -o Rebuild -o NewSignature -o NewAlignment "C:\Downloads\Die in 100 Ways_v1.1.0_apkpure.com.apk"**" in **windows 10**.

apktool, zipalign and jarsigner can be executed through cmd, and apktool is the newest version.

**The error:**

Running obfuscators (Rebuild):  25%|
|[00:45<02:16, 45.53s/obfuscator]26/11/2020 15:42:22> [ERROR][obfuscapk.tool.Apktool][build()] Error during building: "E:\out.apk" was not built correctly. Apktool output:
I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersion' in package 'android'
W:
W: E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anna\AppData\Local\Temp\brut_util_Jar_1897038358374367623.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 26, --version-code, 11, --version-name, 1.1.0, --no-version-vectors, -F, C:\Users\anna\AppData\Local\Temp\APKTOOL15791780235511854090.tmp, -e, C:\Users\anna\AppData\Local\Temp\APKTOOL13132611080915806499.tmp, -0, arsc, -I, C:\Users\anna\AppData\Local\Temp\1.apk, -S, E:\test\Die in 100 Ways_v1.1.0_apkpure.com\res, -M, E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml]
Press any key to continue . . .
26/11/2020 15:42:22> [ERROR][obfuscapk.obfuscation][build_obfuscated_apk()] Error during apk building: "E:\out.apk" was not built correctly. Apktool output:
I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersion' in package 'android'
W:
W: E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anna\AppData\Local\Temp\brut_util_Jar_1897038358374367623.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 26, --version-code, 11, --version-name, 1.1.0, --no-version-vectors, -F, C:\Users\anna\AppData\Local\Temp\APKTOOL15791780235511854090.tmp, -e, C:\Users\anna\AppData\Local\Temp\APKTOOL13132611080915806499.tmp, -0, arsc, -I, C:\Users\anna\AppData\Local\Temp\1.apk, -S, E:\test\Die in 100 Ways_v1.1.0_apkpure.com\res, -M, E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml]
Press any key to continue . . .
26/11/2020 15:42:22> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: "E:\out.apk" was not built correctly. Apktool output:
I: Using Apktool 2.4.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersion' in package 'android'
W:
W: E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anna\AppData\Local\Temp\brut_util_Jar_1897038358374367623.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 26, --version-code, 11, --version-name, 1.1.0, --no-version-vectors, -F, C:\Users\anna\AppData\Local\Temp\APKTOOL15791780235511854090.tmp, -e, C:\Users\anna\AppData\Local\Temp\APKTOOL13132611080915806499.tmp, -0, arsc, -I, C:\Users\anna\AppData\Local\Temp\1.apk, -S, E:\test\Die in 100 Ways_v1.1.0_apkpure.com\res, -M, E:\test\Die in 100 Ways_v1.1.0_apkpure.com\AndroidManifest.xml]
Press any key to continue . . .
...

**Comment by ClaudiuGeorgiu** [comment]
Hi, please try using only `-o Rebuild -o NewSignature -o NewAlignment`, if the issue persists then the error is caused by `apktool`.

**Comment by Coroline** [comment]
Thank you for your quick reply! Problem solved.
