### ISSUE TITLE
Error during Decode command: Invalid file (bad magic number)

### ISSUE THREAD

**Issue by localacct** [ClaudiuGeorgiu/Obfuscapk#66]
### Prerequisites

Before opening this issue, I tried the following steps:

* [*] Installed the tool in a way [described in the readme](https://github.com/ClaudiuGeorgiu/Obfuscapk#-installation) and ran `python3 -m obfuscapk.cli --help` without any errors

* [*] Ran the tool using only `Rebuild`, `NewSignature` and `NewAlignment` obfuscators to verify that the app is not using anti-repackaging techniques

* [*] Ran the tool using `--ignore-libs` flag to exclude third party libraries from the obfuscation

* [*] Checked [FAQ](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/FAQ.md) and [troubleshooting](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md)

* [*] Checked for [existing similar issues on GitHub](https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3AClaudiuGeorgiu/Obfuscapk)

### Description

Error occurred when running this command
````
python3 -m obfuscapk.cli -o Rebuild ~/files/target_release.apk
````

Running ````python3 -m obfuscapk.cli --help```` works and there were no errors

### Steps to reproduce

1. Build a simple test application
2. Try to run obfuscapk on the apk

**Expected behavior:**

The apk should be rebuilt.

**Actual behavior:**

```
[ERROR][obfuscapk.tool.Apktool][decode()] Error during decode command: invalid file (bad magic number): Exec format error
```

### Versions

* **Installation mode** (e.g., from source or with Docker): Source
* **OS** (e.g., Ubuntu 16.04): Ubuntu 20.04
* **Python version** (e.g., 3.7.4): Python 3.8.5
* **Apktool version** (e.g., v2.4.0): 2.5.0

### Additional information

I can manually decompile the apk if I use the following command
````
java -jar apktool_2.5.0.jar d target_release.apk
````

I can manually replicate a similar error message if I omit the "java -jar" portion
````
apktool_2.5.0.jar d target_release.apk
````

My $APKTOOL_PATH is set to the exact file "/home/user/apktool_2.5.0.jar" because if I set it to the containing folder, I get another error ````Something is wrong with executable /home/user/````

**Comment by ClaudiuGeorgiu** [comment]
Hi, you need to also install the wrapper script, as described here: <https://ibotpeaches.github.io/Apktool/install/>.
The `APKTOOL_PATH` has to be set to the path of the wrapper script, not to the jar file directly.

**Comment by localacct** [comment]
Hi @ClaudiuGeorgiu

Sorry, my mistake. Thanks its resolved now.
