### ISSUE TITLE
Should have DEX file obfuscation also

### ISSUE THREAD

**Issue by nighthawkk** [ClaudiuGeorgiu/Obfuscapk#67]
### DEX file obfuscation feature request

It must have a way to obfuscate only DEX file instead of whole apk, i.e; Input will be a DEX file instead of APK.

For Disassembling/Assembling DEX into smali and vice-versa can be done with: baksmali/smali jar files.

**Comment by ClaudiuGeorgiu** [comment]
Hi, the purpose of Obfuscapk is to obfuscate the whole application, so I don't think we will add an option to obfuscate only the dex file(s). Currently the dex files are already obfuscated when using obfuscators belonging to `Code` category, so if you need only the dex files you can extract them from the final apk.
