### ISSUE TITLE
Running Obfuscapk on a bundle of apks 

### ISSUE THREAD

**Issue by saneeha-amir** [ClaudiuGeorgiu/Obfuscapk#68]
I want to use Obfusapk to obfuscate a set of android applications. Is there any way that i can give command to run it over a folder that contains many apk files. I dont want to run it on each apk file as I need to generate a data set of obfuscated samples. Thanks

**Comment by ClaudiuGeorgiu** [comment]
Hi, currently there is no builtin function to obfuscate a set of applications. However, this can be easily implemented, just create a small script that calls the following method for each apk file:
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/4b4b36964eb9a9dc368c91b797642938ca5ac681/src/obfuscapk/cli.py#L167-L180

**Comment by NFIGMT** [comment]
> I want to use Obfusapk to obfuscate a set of android applications. Is there any way that i can give command to run it over a folder that contains many apk files. I dont want to run it on each apk file as I need to generate a data set of obfuscated samples. Thanks

I have the same question, but I have been unsuccessful so far. Could you please share your specific methods and code with me? Thank you.
And I tried adding a loop within the cli.py to execute repeatedly, but it seems that it cannot find the file and only obfuscates the .apk. The folder cannot be found.
