### ISSUE TITLE
support for encrypting classes

### ISSUE THREAD

**Issue by saneeha-amir** [ClaudiuGeorgiu/Obfuscapk#69]
Thanks for your tool..

I wanted to ask if there is any option available through which I cam encrypt classes. 
I have seen support for string and arrays encryption. Is there any option for encryption of classes.

Thanks

**Comment by ClaudiuGeorgiu** [comment]
Hi, currently the only obfuscation technique that directly targets classes is [ClassRename](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/master/src/obfuscapk/obfuscators/class_rename), encryption is only available for strings, assets and native libraries.
