### ISSUE TITLE
Apk is crashing

### ISSUE THREAD

**Issue by nibatafh** [ClaudiuGeorgiu/Obfuscapk#70]
Hello,
app is crashing and I dont know why.all has worked fine but app keeps crashing.note ,Iam using androidstudio under windows10 and python 3.7

**Comment by ClaudiuGeorgiu** [comment]
Hi, please see the [this entry in the FAQ](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/FAQ.md#speech_balloon-the-obfuscation-process-seems-to-finish-without-errors-but-the-resulting-application-does-not-install-or-does-not-work-as-expected).

**Comment by jonathanroze** [comment]
Can you show us command line ? I've an issue like your but only when I used ClassRename option
