### ISSUE TITLE
Decompile result

### ISSUE THREAD

**Issue by jonathanroze** [ClaudiuGeorgiu/Obfuscapk#73]
Hi, 

I'm using Obfuscapk, that generate a folder named as my original APK, and finally make a new .APK

But when I inspect the folder named as my original APK I can see that the Small code is encrypted (variable names)

But if I decompile this new APK with apktool I see that older name of variable (unprotected).

Do you have ideas ?

My command:

`python3 -m obfuscapk.cli -o Nop -o Goto -o RandomManifest -o Rebuild -o NewAlignment -o ClassRename -o ConstStringEncryption -o FieldRename -o LibEncryption -o MethodOverload -o NewSignature -o MethodRename -o Reorder -o ResStringEncryption  -w /path/to/dev -d /path/to/dev/of.apk --keystore-file "/path/to/my-key.keystore" --keystore-password "pass" --key-alias "my-key-alias" --key-password "pass"  "/path/to/apk/app-release.apk"`

**Comment by Hoppuc** [comment]
[The order of the obfuscators matter](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/FAQ.md#speech_balloon-is-the-order-of-the-obfuscators-passed-as-parameters-important). In your case APK builds before executing rename obfuscators.

**Comment by jonathanroze** [comment]
Thank you @Hoppuc it works !
