### ISSUE TITLE
Simple -o Rebuild -o NewSignature -o NewAlignment makes APK broken

### ISSUE THREAD

**Issue by trafficteam7** [ClaudiuGeorgiu/Obfuscapk#77]
Hello!
I used next command:
`python3 -m obfuscapk.cli -o Rebuild -o NewSignature -o NewAlignment -i -p app-debug.apk`
The operation was successful. But I can't install result APK.
I receive such error:
![Error](https://i.ibb.co/rcwFQhd/Screenshot-at-Mar-18-21-06-02.png)

**Comment by trafficteam7** [comment]
Found solution for me. Chose obfuscators, the last one is -o Rebuild.
Than align obfuscated apk file with **zipalign**, I used the next command:
`zipalign -p 4 app-debug_obfuscated.apk outline.apk`
After that sign outline.apk with **apksigner**, I used the next command:
`apksigner sign --ks key.jks signed.apk` - you should paste your keystore pass and key pass.
And thats all, you receive signed apk.

**Comment by ClaudiuGeorgiu** [comment]
Hi @trafficteam7, thanks for reporting the issue and the solution. We will use `apksigner` instead of `jarsigner` in a future release of Obfuscapk, so issues like this should be solved (hopefully).
