### ISSUE TITLE
Error when obfuscating 

### ISSUE THREAD

**Issue by aldwnesx** [ClaudiuGeorgiu/Obfuscapk#79]
(venv) C:\Users\john\Projects\Program\gui\Obfuscapk\src>python -m obfuscapk.cli -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment "../../whatsapp.apk"
27/03/2021 13:25:55> [ERROR][obfuscapk.tool.Apktool][build()] Error during building: "../..\obfuscation_working_dir\whatsapp_obfuscated.apk" was not built correctly. Apktool output:
I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
I: Building resources...
W: Failed to generate resource table for split ''
W: C:\Users\john\Projects\Program\gui\Obfuscapk\src\..\..\obfuscation_working_dir\whatsapp\res\values\drawables.xml:18: error: Error: String types not allowed (at 'APKTOOL_DUMMY_24a' with value '').
W:

**Comment by aldwnesx** [comment]
Also tried with different methods

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '../..\\obfuscation_working_dir\\whatsapp\\smali\\X\\1eO.2.smali' -> '../..\\obfuscation_working_dir\\whatsapp\\smali\\X\\1eO.2.smali.bak'

**Comment by ClaudiuGeorgiu** [comment]
One of the prerequisites is running the tool using `python3 -m obfuscapk.cli -o Rebuild -o NewSignature -o NewAlignment <YOUR_APP.APK>` to verify that the app is not using anti-repackaging techniques. Well, I guess WhatsApp is using some anti-repackaging techniques 😅.

**Comment by aldwnesx** [comment]
> One of the prerequisites is running the tool using `python3 -m obfuscapk.cli -o Rebuild -o NewSignature -o NewAlignment <YOUR_APP.APK>` to verify that the app is not using anti-repackaging techniques. Well, I guess WhatsApp is using some anti-repackaging techniques 😅.

Thanks for your reply. After running the prerequisites, what do I expect to see if I can continue issuing this tool?

**Comment by aldwnesx** [comment]
> One of the prerequisites is running the tool using `python3 -m obfuscapk.cli -o Rebuild -o NewSignature -o NewAlignment <YOUR_APP.APK>` to verify that the app is not using anti-repackaging techniques. Well, I guess WhatsApp is using some anti-repackaging techniques 😅.

or is there any APK I can test?

**Comment by ClaudiuGeorgiu** [comment]
> Thanks for your reply. After running the prerequisites, what do I expect to see if I can continue issuing this tool?

The command should end without any error: this means the application can at least be repackaged. You can find a very basic test application [here](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/4b4b36964eb9a9dc368c91b797642938ca5ac681/src/test/test_resources/v1.0).
