### ISSUE TITLE
file path error

### ISSUE THREAD

**Issue by aldwnesx** [ClaudiuGeorgiu/Obfuscapk#80]
everytime i try to run the command, it always append invalid file path:

NotADirectoryError: Unable to find source directory "C:/Users/jn/newfoldr\obfuscation_working_dir\com.obfuscapk.demo.v1.0-original"

when the filepath i specify via command:

python -m obfuscapk.cli -o Rebuild -o NewSignature -o ClassRename "C:/Users/jn/newfoldr/
com.obfuscapk.demo.v1.0-original.apk"

**Comment by ClaudiuGeorgiu** [comment]
Can you try the command `python -m obfuscapk.cli -o ClassRename -o Rebuild -o NewSignature "C:\Users\jn\newfoldr\com.obfuscapk.demo.v1.0-original.apk"`? Do you get the same error?

**Comment by bdstar** [comment]
I have got the following error,
```
(myenv) E:\code\Obfuscapk\src>python -m obfuscapk.cli --help
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\code\Obfuscapk\src\obfuscapk\cli.py", line 189, in <module>
    main()
  File "E:\code\Obfuscapk\src\obfuscapk\cli.py", line 140, in main
    check_external_tool_dependencies()
  File "E:\code\Obfuscapk\src\obfuscapk\main.py", line 41, in check_external_tool_dependencies
    Apktool()
  File "E:\code\Obfuscapk\src\obfuscapk\tool.py", line 30, in __init__
    'Something is wrong with executable "{0}"'.format(self.apktool_path)
RuntimeError: Something is wrong with executable "D:\apktool"
```
I have added an environment variable APKTOOL_PATH = D:\apktool
But still showing the above error. What's wrong with me?

**Comment by ClaudiuGeorgiu** [comment]
What is `D:\apktool`? On Windows, you should have 2 files (as described [here](https://ibotpeaches.github.io/Apktool/install/)): `apktool.bat` and `apktool.jar`, `APKTOOL_PATH` expects the path to the `.bat` file.
