### ISSUE TITLE
Obfuscation paused in between

### ISSUE THREAD

**Issue by ArchanaNair** [ClaudiuGeorgiu/Obfuscapk#87]
Hi,

I am trying to run a basic command like below, but obfuscation paused in between, what could be the error here? 

python3.7 -m obfuscapk.cli -p -d /.../obfuscated.apk -o Rebuild -o NewSignature -o NewAlignment /.../app-dev-release.apk

Running obfuscators (NewSignature):  33%|█████████████▋                           |[00:31<01:02, 31.09s/obfuscator]

**Comment by ClaudiuGeorgiu** [comment]
Hi, try [enabling the verbose logging](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/master/docs/TROUBLESHOOTING.md#enable-verbose-logging) to better understand what's going on. If the obfuscation is stuck on `NewSignature` maybe there is some problem with the underlying `apksigner`.

**Comment by ArchanaNair** [comment]
@ClaudiuGeorgiu , thanks for the quick response. I have enabled log, 
As you said it got stuck in newsignature.

I have set the path of apksigner as below in MAC OS, environment  variable. 

export APKSIGNER_PATH=/../Library/Android/sdk/build-tools/29.0.3/apksigner                                         
export ZIPALIGN_PATH=/../Library/Android/sdk/build-tools/29.0.3/zipalign

I am not sure what causing apksigner issue? Please advise

**Comment by ArchanaNair** [comment]
Added to above question, i have moved my keystore file to resource folder and used that path in obfuscation.py file as below
 self.keystore_file = os.path.join(
                os.path.dirname(__file__), "resources", "xxx.keystore"
            )
Is it correct way? do I need to convert .keystore to .jks?

**Comment by ArchanaNair** [comment]
I am able to resolve above error by passing  self.key_password ="XXXX" in  obfuscation.py file.
Now obfuscating apk is created. But another issues is that, I am unable to install apk on my phone to verify.
Is this because the apk got corrupted, or some other issue? I am getting "App Not Installed" error on tapping the apk
 below is the command I have used 
 python3.7 -m obfuscapk.cli -o ConstStringEncryption -o CallIndirection -o Goto -o Rebuild -o NewSignature -o NewAlignment /Users/..../app-dev-release.apk

 output in terminal
unning obfuscators (ConstStringEncryption):   0%|                  |[00:00<?, ?obfuscator/s]
Encrypting constant strings:   2%|▊                                |[00:00<00:07, 927.76file/s]
Encrypting constant strings:   3%|█▍                                        |[00:00<00:08, 856.97file/s]
Encrypting constant strings: 100%|████████████████████████████████████████████████|[00:15<00:00, 455.64file/s]
Inserting call indirections in smali files:   5%|█▋                               |[00:00<00:12, 551.07file/s]
Inserting "goto" instructions in smali files: 100%|██████████████████████████████|[00:06<00:00, 1075.42file/s]
Running obfuscators (NewAlignment): 100%|████████████████████████████████████████████|[01:01<00:00, 10.26s/obfuscator]

**Comment by ArchanaNair** [comment]
I am using comment like below

python3.7 -m obfuscapk.cli -o ConstStringEncryption -o Goto -o Rebuild -o NewSignature -o NewAlignment -p /Users/.../app-dev-release.apk --keystore-file /Users/.../key/xxxkeystore --[keystore-password storepwd] [--key-alias alias] [--key-password keypass]

O/P: Without any error, it is executing. But when I am trying to install obfuscated apk on my Device, It gives me an error that 
"App Not Installed". Is there any chance of apk got corrupted?

Encrypting constant strings: 100%|██████████████████████████████████|[00:11<00:00, 634.70file/s]
Inserting "goto" instructions in smali files: 100%|████████████████|[00:05<00:00, 1278.08file/s]
Running obfuscators (NewAlignment): 100%|██████████████████████|[00:49<00:00,  9.91s/obfuscator]
