### ISSUE TITLE
Rename obfuscators cause crashes

### ISSUE THREAD

**Issue by clockdev** [ClaudiuGeorgiu/Obfuscapk#89]
Hello!

After achieving a satisfactory result with the obfuscators, I began to test the applications for performance. And, it turned out that most of the obfuscators from the Rename category break the apk.

At first, I thought it was my apk that was the problem. I created an empty Java project in Android Studio with one Activity, compiled it into an apk and started checking the obfuscators one by one.

As soon as I started using obfuscators from the Rename category, the freshly created app stopped launching.

I tested the following obfuscators, exactly in that sequence:

14. MethodRename, Rebuild, NewAlignment, NewSignature
13. FieldRename, Rebuild, NewAlignment, NewSignature
12. ClassRename, Rebuild, NewAlignment, NewSignature

The logs for all of these crashes are here: https://gist.github.com/clockdev/2f1a8ddede1e78259b148a8202f862f5

I have a suspicion that all these crashes are related, what could be the fault of these crashes?

**Comment by Therahuls1n9h** [comment]
same issue i'm facing any solution??
