### ISSUE TITLE
Can classes that implement specific interfaces prohibit obfuscation?

### ISSUE THREAD

**Issue by luowl123** [ClaudiuGeorgiu/Obfuscapk#91]
Can classes that implement specific interfaces prohibit obfuscation?
just like proguard
```
-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}
```

**Comment by ClaudiuGeorgiu** [comment]
Hi @luowl123, currently it's not possibile, but it could be an interesting improvement.
