### ISSUE TITLE
error during ofuscation

### ISSUE THREAD

**Issue by pretech86** [ClaudiuGeorgiu/Obfuscapk#93]
i get this error on kali linux 

python3.7 -m obfuscapk.cli -p -w /tools/Obfuscapk/src  -d /tools/Obfuscapk/src/obfuscated.apk -o ConstStringEncryption -o Nop -o Goto -o RandomManifest -o Rebuild -o NewSignature -o NewAlignment /root/Desktop/SALYOO.apk 

Encrypting constant strings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████|[00:05<00:00, 197.10file/s]

Inserting "nop" instructions in smali files: 100%|██████████████████████████████████████████████████████████████████████████████████████████|[00:02<00:00, 487.40file/s]

Inserting "goto" instructions in smali files: 100%|█████████████████████████████████████████████████████████████████████████████████████████|[00:01<00:00, 611.29file/s]

Running obfuscators (Rebuild):  43%|██████████████████████████████████████████▍                                                        |[00:26<00:46, 11.72s/obfuscator]09/05/2021 06:13:39> [ERROR][obfuscapk.tool.Apktool][build()] Error during build command: Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

I: Using Apktool 2.4.1-dirty

I: Smaling smali folder into classes.dex...

I: Building resources...

W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)

W: First type is not attr!

W: A/        ( 3658): First type is not attr!

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL3978750084439979478.tmp, -0, resources.arsc, -0, png, -0, arsc, -I, /tmp/1.apk, -S, /tools/Obfuscapk/src/SALYOO/res, -M, /tools/Obfuscapk/src/SALYOO/AndroidManifest.xml]

09/05/2021 06:13:39> [ERROR][obfuscapk.obfuscation][build_obfuscated_apk()] Error during apk building: Command '['/usr/bin/apktool', '--frame-path', '/tmp', 'b', '--force-all', '/tools/Obfuscapk/src/SALYOO', '-o', '/tools/Obfuscapk/src/obfuscated.apk']' returned non-zero exit status 1.

09/05/2021 06:13:39> [ERROR][yapsy_loaded_plugin_Rebuild_1.rebuild.Rebuild][obfuscate()] Error during execution of "Rebuild" obfuscator: Command '['/usr/bin/apktool', '--frame-path', '/tmp', 'b', '--force-all', '/tools/Obfuscapk/src/SALYOO', '-o', '/tools/Obfuscapk/src/obfuscated.apk']' returned non-zero exit status 1.

09/05/2021 06:13:39> [CRITICAL][obfuscapk.main][perform_obfuscation()] Error during obfuscation: Command '['/usr/bin/apktool', '--frame-path', '/tmp', 'b', '--force-all', '/tools/Obfuscapk/src/SALYOO', '-o', '/tools/Obfuscapk/src/obfuscated.apk']' returned non-zero exit status 1.

Traceback (most recent call last):

  File "/root/tools/Obfuscapk/src/obfuscapk/main.py", line 151, in perform_obfuscation

    (obfuscator_name_to_function[obfuscator_name])(obfuscation)

  File "/root/tools/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate

    obfuscation_info.build_obfuscated_apk()

  File "/root/tools/Obfuscapk/src/obfuscapk/obfuscation.py", line 507, in build_obfuscated_apk

    self._decoded_apk_path, self.obfuscated_apk_path, self.use_aapt2

  File "/root/tools/Obfuscapk/src/obfuscapk/tool.py", line 167, in build

    build_cmd, stderr=subprocess.STDOUT, input=b"\n"

  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output

    **kwargs).stdout

  File "/usr/lib/python3.7/subprocess.py", line 512, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/usr/bin/apktool', '--frame-path', '/tmp', 'b', '--force-all', '/tools/Obfuscapk/src/SALYOO', '-o', '/tools/Obfuscapk/src/obfuscated.apk']' returned non-zero exit status 1.

Running obfuscators (Rebuild):  57%|████████████████████████████████████████████████████████▌                                          |[00:41<00:31, 10.37s/obfuscator]

Traceback (most recent call last):

  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/root/tools/Obfuscapk/src/obfuscapk/cli.py", line 188, in <module>

    main()

  File "/root/tools/Obfuscapk/src/obfuscapk/cli.py", line 183, in main

    arguments.use_aapt2,

  File "/root/tools/Obfuscapk/src/obfuscapk/main.py", line 151, in perform_obfuscation

    (obfuscator_name_to_function[obfuscator_name])(obfuscation)

  File "/root/tools/Obfuscapk/src/obfuscapk/obfuscators/rebuild/rebuild.py", line 20, in obfuscate

    obfuscation_info.build_obfuscated_apk()

  File "/root/tools/Obfuscapk/src/obfuscapk/obfuscation.py", line 507, in build_obfuscated_apk

    self._decoded_apk_path, self.obfuscated_apk_path, self.use_aapt2

  File "/root/tools/Obfuscapk/src/obfuscapk/tool.py", line 167, in build

    build_cmd, stderr=subprocess.STDOUT, input=b"\n"

  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output

    **kwargs).stdout

  File "/usr/lib/python3.7/subprocess.py", line 512, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/usr/bin/apktool', '--frame-path', '/tmp', 'b', '--force-all', '/tools/Obfuscapk/src/SALYOO', '-o', '/tools/Obfuscapk/src/obfuscated.apk']' returned non-zero exit status 1.

**Comment by ClaudiuGeorgiu** [comment]
Hi, can you try using the latest version of Apktool (2.5.0)?

**Comment by whorohitkumar** [comment]
Im using latest version of apktool 2.5.0 and im facing the same issue when im trying with apk with sdk30, but its working well till older version of sdk can u tell how to fix that
