### ISSUE TITLE
Run obfuscator on multiple apks

### ISSUE THREAD

**Issue by TahaR9** [ClaudiuGeorgiu/Obfuscapk#97]
Just wanna ask a simple question, is it possible to run it inside a directory full of apks, on every apk inside directory using python. If so, how do I do it?

Secondly, is it possible to just generate obfuscated apk file and not other stuff (like it decompiles apk with all its data in directory )

**Comment by ClaudiuGeorgiu** [comment]
Hi,

> Just wanna ask a simple question, is it possible to run it inside a directory full of apks, on every apk inside directory using python. If so, how do I do it?

That's not implemented currently, but you can modify the following code: make a loop and call this snippet for each file you want to obfuscate (only `arguments.apk_file` parameter has to change for each file).

https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/4072b6dea88e91b75064a84c7d3adebe005e8207/src/obfuscapk/cli.py#L170-L184

> Secondly, is it possible to just generate obfuscated apk file and not other stuff (like it decompiles apk with all its data in directory)

The "other stuff" is needed for the obfuscation to work, so it's not possibile to skip the creation of those files. However, after the obfuscation finishes, those files are not needed anymore so we could add a command to delete them (currently they are left on the system for debug purposes, but it's not mandatory).
